### ISSUE TITLE
Bug : Component > Set Password > Remove ABP keys

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#100]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/1a0df804-fb22-4a7d-8c44-4340496b2961)

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/fe075d35-a2d1-440f-8b4f-b1e321d5bc32)
