### ISSUE TITLE
Design System > Build Verification > [Version 1.1.8.6] received on 8thNov 2024

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1024]
Design System > Build Verification > [Version 1.1.8.6] received on 8thNov 2024

**Comment by trivenikulkarni** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

<div data-view-component=true style='box-sizing: border-box;border-bottom:var(--borderWidth-thin) solid var(--borderColor-default);
padding:var(--stack-padding-normal);font-variant-ligatures: normal;font-variant-caps: normal;
orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>


Sr.No | PR | GitHub   Link | Status | Remark | Dev | QA
-- | -- | -- | -- | -- | -- | --
1 | Completed   Task 777 : Design System > Elements > Enhancements in file uploader   by @abhijeetjawale1 in #957 |   |   |   |   |  
2 | Resolved   Bug 862 : Design System > Components > Alert Popup > Default >   Popup cancel delete button is not working by @DeepashriDatar in #983 |   |   |   |   |  
3 | Resolved   Bug 749 : Design System > Element > Alert : Alert issues by @nitinsonawane123 in #986 |   |   |   |   |  
4 | Resolved   Bug 969 : Design System >Elements > Payment Card > Default >   Label and button alignment issue by @nitinsonawane123 in #980 |   |   |   |   |  
5 | Resolved   Bug 810 : Component > Datatable > Action button on Left side > Not   able to see the 'Edit' option after hovering over the row below in the table   by @VenuKG in #985 |   |   |   |   |  
6 | Resolved   Bug 892 : Design System > Components > Testimonials > Default >   UI issues by @poojagurav21 in #955 |   |   |   |   |  
7 | Resolved   Bug 671 : Storybook > Component > Forms basic > Required message is   not display by @nitinsonawane123 in #993 |   |   |   |   |  
8 | Completed   Task 742 : Badge minor issue & enhancement is completed by @suchithravipin1991 in #998 |   |   |   |   |  
9 | Resolved   Bug 752 : Design System > Badge Minor issue resolved by @suchithravipin1991 in #757 |   |   |   |   |  
10 | Completed   Task 1001 : Elements > Enhancement > Nav Tab : Enhancements in nav tab   > File Mover : Dynamic Icons > New Element > Button Grid by @DeepashriDatar in #1010 |   |   |   |   |  
11 | Resolved   Bug 659 : Storybook > Components > Contact Us > Default >   Displaying multiple error messages at the one time by @nitinsonawane123 in #1004 |   |   |   |   |  
12 | Completed   Task 981 : Design-system > Create icon for custom images for RDS icon   by @rahulp34 in #1012 |   |   |   |   |  
13 | Completed   Task 938 : Design system enhancement in checkbox as per new project flow   by @rahulp34 in #939 |   |   |   |   |  
14 | Resolved   Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top   button is not visible. by @abhijeetjawale1 in #1023 |   |   |   |   |  
15 | Resolved   Bug 807 : Design System > Charts > Polar Area Chart > Change theme   and size display error massage by @abhijeetjawale1 in #1025 |   |   |   |   |  
16 | Completed   Task 900 : Design System > Element > Create new element Time Picker   by @abhijeetjawale1 in #1028 |   |   |   |   |  
17 | Resolved   Bug 1027 : Design System > Charts >Bubble Charts >Click on Outline   to the preview & enable measures show error by @abhijeetjawale1 in #1034 |   |   |   |   |  
18 | Completed   Task 592 : Design System > Implement different types of Avtaars by @abhijeetjawale1 in #1030 |   |   |   |   |  
19 | Resolved   Bug 690 : Design System > Components > Data Table > Add new   component for Action by @abhijeetjawale1 in #1015 |   |   |   |   |  
20 | Resolved   Bug 894 : Component > Visual Setting > default > mobile view (small   & large) footer overlapping issue & other changes by @DeepashriDatar in #1035 |   |   |   |   |  
21 | Resolved   Bug 898 : Design System > Components > Claim Type & Language >   Default > After submission dropdown field does not clear & some label   changes by @DeepashriDatar in #1020 |   |   |   |   |  
22 | Resolved   Bug 814 : Component > Product list > Product list with Inline price   > small mobile > Not able to see full image by @nitinsonawane123 in #1026 |   |   |   |   |  
23 | Resolved   Bug 1005 : Design System > Components> Claims > Default > Plus   button alignment issue by @nitinsonawane123 in #1022 |   |   |   |   |  
24 | Resolved   Bug 1029 : Components >Admin Dashboard > UI does not display proper.   by @nitinsonawane123 in #1031 |   |   |   |   |  
25 | Completed   Task 995 : Design System > Element > Add new element for header   by @poojagurav21 in #1007 |   |   |   |   |  
26 | Completed   Task 996 : Design System > Element > Enhancement in Divider by @poojagurav21 in #1006 |   |   |   |   |  
27 | Resolved   Bug 885 : Design System > Components > Payment Tenure > Default >   After submitting field not clear and data is not display in action by @prakashmhaske in #979 |   |   |   |   |  
28 | Resolved   Bug 991 : Design System > Components > Calendar > Small mobile view   text and alignment issue by @prakashmhaske in #1016 |   |   |   |   |  
29 | Completed   Task 850 : Design System > Element > Progress Bar > Enhancements in   style for Circular by @rohit9096 in #877 |   |   |   |   |  
30 | Completed   Task 1014 : Design System > Elements > Text changes in element name   by @rahulp34 in #1021 |   |   |   |   |  
31 | Completed   Task 902 : Design System > Element > Create new element Truncated Text   by @suchithravipin1991 in #942 |   |   |   |   |  
32 | Completed   Task 1013 : Design System > Element > Add New Story for Stepper with   checkbox by @rahulp34 in #1036 |   |   |   |   |  
33 | Completed   Task 786 : Design System > Elements > Enhancements in pagination   by @abhijeetjawale1 in #1043 |   |   |   |   |  
34 | Completed   Task 999 : Design System > Component > Card : Enhancement in card view   by @poojagurav21 in #1037 |   |   |   |   |  
35 | Completed   Task 796 : Design System > Elements > Enhancements in Review by @prakashmhaske in #937 |   |   |   |   |  
36 | Completed   Task 794 : Design System > Elements > Enhancements in breadcrumb   by @poojagurav21 in #968 |   |   |   |   |  
37 | Completed   Task 796 : Design System > Elements > Enhancements in Review by @poojagurav21 in #1045 |   |   |   |   |  
38 | Completed   Task 962 : Design System > Element > Create new element file uploader   with avatar by @rahulp34 in #1048 |   |   |   |   |  
39 | Merge   Development : Moving Changes from Development to Staging Branch by @hemalatagaikwad in #1057 |   |   |   |   |  



</body>

</html>

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

<div ccp_infra_version=3 ccp_infra_timestamp=1731477787750 ccp_infra_user_hash=638462020
ccp_infra_copy_id="" data-ccp-timestamp=1731477787750>


Sr.No | PR | GitHub Link | Status | Remark | Dev | QA
-- | -- | -- | -- | -- | -- | --
1 | Resolved   Bug 862 : Design System > Components > Alert Popup > Default >   Popup cancel delete button is not working by @DeepashriDatar in #983 | Design   System > Components > Alert Popup > Default > Popup cancel delete   button is not working. · Issue #862 · Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Deepashri | Rameshwar
2 | Completed   Task 796 : Design System > Elements > Enhancements in Review by @poojagurav21 in #1045 | Design   System > Elements > Enhancements in Review · Issue #796 ·   Wai-Technologies/raaghu-react | PR Approved | Reopen | Pooja | Rameshwar
3 | Resolved   Bug 749 : Design System > Element > Alert : Alert issues by @nitinsonawane123 in #986 | Design   System > Element > Alert : Alert issues · Raaghu Design System | Ready for QA | Reopen | Nitin | Rameshwar
4 | Resolved   Bug 969 : Design System >Elements > Payment Card > Default >   Label and button alignment issue by @nitinsonawane123 in #980 | Design   System >Elements > Payment Card > Default > Label and button   alignment issue. · Issue #969 · Wai-Technologies/raaghu-react | Ready for QA | Reopen | Nitin | Rameshwar
5 | Resolved   Bug 810 : Component > Datatable > Action button on Left side > Not   able to see the 'Edit' option after hovering over the row below in the table   by @VenuKG in #985 | Design   System > Version 8.3 > Component > Datatable > Action button on   Left side > Not able to see the 'Edit' option after hovering over the row   below in the table · Issue #810 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Venu | Rameshwar
6 | Resolved   Bug 892 : Design System > Components > Testimonials > Default >   UI issues by @poojagurav21 in #955 | Design   System > Components > Testimonials > Default > UI issues. · Issue   #892 · Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Pooja | Rameshwar
7 | Resolved   Bug 671 : Storybook > Component > Forms basic > Required message is   not display by @nitinsonawane123 in #993 | Storybook   > Component > Forms basic > Required message is not display. · Issue   #671 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Nitin | Rameshwar
8 | Completed   Task 742 : Badge minor issue & enhancement is completed by @suchithravipin1991 in #998 | Design   System > Elements > Badge : Minor issues in Badge · Issue #752 ·   Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
9 | Resolved   Bug 752 : Design System > Badge Minor issue resolved by @suchithravipin1991 in #757 | Design   System > Elements > Badge : Minor issues in Badge · Issue #752 ·   Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
10 | Completed   Task 1001 : Elements > Enhancement > Nav Tab : Enhancements in nav tab   > File Mover : Dynamic Icons > New Element > Button Grid by @DeepashriDatar in #1010 | Design   System > Elements > Enhancement >Nav Tab : Enhancements in nav tab   > File Mover : Dynamic Icons > New Element > Button Grid · Issue   #1001 · Wai-Technologies/raaghu-react | PR Approved | Reopen | Deepashri | Rameshwar
11 | Resolved   Bug 659 : Storybook > Components > Contact Us > Default >   Displaying multiple error messages at the one time by @nitinsonawane123 in #1004 | Storybook   > Components > Contact Us > Default > Displaying multiple error   messages at the one time. · Issue #659 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Nitin | Rameshwar
12 | Completed   Task 981 : Design-system > Create icon for custom images for RDS icon   by @rahulp34 in #1012 | Design-system   > Create icon for custom images for RDS icon · Issue #981 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Rahul | Rameshwar
13 | Completed   Task 938 : Design system enhancement in checkbox as per new project flow   by @rahulp34 in #939 | Design   System > Enhancement in checkbox as per new project flow · Issue #938 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Rahul | Rameshwar
14 | Resolved   Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top   button is not visible. by @abhijeetjawale1 in #1023 | Design   System > Elements > Scrollspy > Dark theme Go Top button is not   visible. · Issue #789 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Abhijeet | Rameshwar
15 | Resolved   Bug 807 : Design System > Charts > Polar Area Chart > Change theme   and size display error massage by @abhijeetjawale1 in #1025 | Design   System > Charts > Polar Area Chart > Change theme and size display   error massage. · Issue #807 · Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
16 | Completed   Task 900 : Design System > Element > Create new element Time Picker   by @abhijeetjawale1 in #1028 | Design   System > Element > Create new element Time Picker. · Issue #900 ·   Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Abhijeet | Rameshwar
17 | Resolved   Bug 1027 : Design System > Charts >Bubble Charts >Click on Outline   to the preview & enable measures show error by @abhijeetjawale1 in #1034 | Design   System > Charts >Bubble Charts >Click on Outline to the preview   & enable measures show error. · Issue #1027 ·   Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Abhijeet | Rameshwar
18 | Completed   Task 592 : Design System > Implement different types of Avtaars by @abhijeetjawale1 in #1030 | Design   System > Implement different types of Avtaars · Issue #592 ·   Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
19 | Resolved   Bug 690 : Design System > Components > Data Table > Add new   component for Action by @abhijeetjawale1 in #1015 | Design   System > Components > Data Table > Add new component for Action ·   Issue #690 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Abhijeet | Rameshwar
20 | Resolved   Bug 894 : Component > Visual Setting > default > mobile view (small   & large) footer overlapping issue & other changes by @DeepashriDatar in #1035 | Design   System > Components > Visual Setting> Default > Small large   mobile Subheader Footer overlap. · Issue #894 · Wai-Technologies/raaghu-react | PR Approved | Reopen | Deepashri | Rameshwar
21 | Resolved   Bug 898 : Design System > Components > Claim Type & Language >   Default > After submission dropdown field does not clear & some label   changes by @DeepashriDatar in #1020 | Design   System > Components > Claim Type > Default >After submitting   field not clear. · Issue #898 · Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Deepashri | Rameshwar
22 | Resolved   Bug 814 : Component > Product list > Product list with Inline price   > small mobile > Not able to see full image by @nitinsonawane123 in #1026 | Design   System > Version 8.3 > Component > Product list > Product list   with Inline price > small mobile > Not able to see full image · Issue   #814 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Nitin | Rameshwar
23 | Resolved   Bug 1005 : Design System > Components> Claims > Default > Plus   button alignment issue by @nitinsonawane123 in #1022 | Design   System > Components> Claims > Default > Plus button alignment   issue. · Issue #1005 · Wai-Technologies/raaghu-react | Ready for QA | Reopen | Nitin | Rameshwar
24 | Resolved   Bug 1029 : Components >Admin Dashboard > UI does not display proper.   by @nitinsonawane123 in #1031 | Design   System > Components >Admin Dashboard > UI does not display proper. ·   Issue #1029 · Wai-Technologies/raaghu-react | Ready for QA | Ready   For Prod | Nitin | Rameshwar
25 | Completed   Task 995 : Design System > Element > Add new element for header   by @poojagurav21 in #1007 | Design   System > Element > Add new element for header · Issue #995 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Pooja | Rameshwar
26 | Completed   Task 996 : Design System > Element > Enhancement in Divider by @poojagurav21 in #1006 | Design   System > Element > Enhancement in Divider · Issue #996 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Pooja | Rameshwar
27 | Resolved   Bug 885 : Design System > Components > Payment Tenure > Default >   After submitting field not clear and data is not display in action by @prakashmhaske in #979 | Design   System > Components > Payment Tenure > Default > After submitting   field not clear and data is not display in action. · Issue #885 ·   Wai-Technologies/raaghu-react | PR Approved | Reopen | Prakash | Rameshwar
28 | Resolved   Bug 991 : Design System > Components > Calendar > Small mobile view   text and alignment issue by @prakashmhaske in #1016 | Design   System > Components > Calendar > Small mobile view text and   alignment issue. · Issue #991 · Wai-Technologies/raaghu-react | PR Approved | Reopen | Prakash | Rameshwar
29 | Completed   Task 850 : Design System > Element > Progress Bar > Enhancements in   style for Circular by @rohit9096 in #877 | Design   System > Element > Progress Bar > Enhancements in style for Circular   · Issue #850 · Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Rahul | Rameshwar
30 | Completed   Task 1014 : Design System > Elements > Text changes in element name   by @rahulp34 in #1021 | Design   System > Elements > Text changes in element name · Issue #1014 ·   Wai-Technologies/raaghu-react | PR Approved | Reopen | Rahul | Rameshwar
31 | Completed   Task 902 : Design System > Element > Create new element Truncated Text   by @suchithravipin1991 in #942 | Design   System > Element > Create new element Truncated Text. · Issue #902 ·   Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
32 | Completed   Task 1013 : Design System > Element > Add New Story for Stepper with   checkbox by @rahulp34 in #1036 | Design   System > Element > Add New Story for Stepper with checkbox · Issue   #1013 · Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Rahul | Rameshwar
33 | Completed   Task 786 : Design System > Elements > Enhancements in pagination   by @abhijeetjawale1 in #1043 | Design   System > Elements > Enhancements in pagination · Issue #786 ·   Wai-Technologies/raaghu-react | Ready for QA | Reopen | Abhijeet | Rameshwar
34 | Completed   Task 999 : Design System > Component > Card : Enhancement in card view   by @poojagurav21 in #1037 | Design   System > Component > Card : Enhancement in card view · Issue #999 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Pooja | Rameshwar
35 | Completed   Task 796 : Design System > Elements > Enhancements in Review by @prakashmhaske in #937 | Design   System > Elements > Enhancements in Review · Issue #796 ·   Wai-Technologies/raaghu-react | PR Approved | Reopen | Pooja | Rameshwar
36 | Completed   Task 794 : Design System > Elements > Enhancements in breadcrumb   by @poojagurav21 in #968 | Design   System > Elements > Enhancements in breadcrumb · Issue #794 ·   Wai-Technologies/raaghu-react | PR Approved | Ready   For Prod | Pooja | Rameshwar
37 | Completed   Task 777 : Design System > Elements > Enhancements in file uploader   by @abhijeetjawale1 in #957 | Design   System > Elements > Enhancements in file uploader · Issue #777 ·   Wai-Technologies/raaghu-react | Ready for QA | Done | Abhijeet | Rameshwar
38 | Completed   Task 962 : Design System > Element > Create new element file uploader   with avatar by @rahulp34 in #1048 | Design   System > Element > Create new element file uploader with avatar · Issue   #962 · Wai-Technologies/raaghu-react | PR Approved | Reopen | Rahul | Rameshwar
  |   |   |   |   |   |  



</body>

</html>
Ready for Prod - 21
Reopen - 17
