### ISSUE TITLE
Bug : Issues on Element > Button Group > Icon Button Group > Update mouse hovering color to violet (Raaghu by default button color)

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#108]
On mouse hovering violet color should display with icons

Expected result- 

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/7c67f20a-026c-40ca-8a93-5f1bee44e08f)

Actual result -

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/28698af3-d17b-4e7a-ad2d-8cb6a43f4923)

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/945be814-407b-410e-9022-ca528900881d)
