### ISSUE TITLE
Design System -> Build verification - [Version 1.1.8.7] received on 18th Nov

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1117]
Design System -> Build verification - [Version 1.1.8.7] received on 18th Nov
https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8.7(s)
![image](https://github.com/user-attachments/assets/712a53ed-5ec7-4d1e-9474-f1bdde2461e7)

**Comment by rameshwarkamandar** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">



</head>

<body lang=EN-IN link="#467886" vlink="#96607D" style='tab-interval:36.0pt;
word-wrap:break-word'>


<p class=MsoNormal><span style='font-size:11.0pt'>Ready for Prod - 6<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'>Reopen - 1<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Aptos Narrow",sans-serif;
color:black;mso-ligatures:none;mso-fareast-language:EN-IN'>Already Closed - 5<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Aptos Narrow",sans-serif;
color:black;mso-ligatures:none;mso-fareast-language:EN-IN'>In progress – 1<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Aptos Narrow",sans-serif;
color:black;mso-ligatures:none;mso-fareast-language:EN-IN'>PR Approved - 1<o:p></o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt;font-family:"Aptos Narrow",sans-serif;
color:black;mso-ligatures:none;mso-fareast-language:EN-IN'><o:p>&nbsp;</o:p></span></p>


Sr.No | PR | GitHub Link | Status | Remark | Dev | QA
-- | -- | -- | -- | -- | -- | --
1 | Resolved Bug 766: Elements > Button > Size   not working proper selecting large size change by @DeepashriDatar in #888 | Design   System > Version 8.3.3 >Elements > Button > Size not working   proper selecting large size change the background icon. · Issue #766 ·   Wai-Technologies/raaghu-react | PR Approved |   | Deepashri | Rameshwar
2 | Completed Task 781 : Design System > Version   8.3.3 > side nav bar > excess space is showing between two components   by @abhijeetjawale1 in #891 | Design   System > Version 8.3.3 > side nav bar > excess space is showing   between two components · Issue #781 · Wai-Technologies/raaghu-react |   | Already Closed | Abhijeet | Rameshwar
3 | Resolved Bug 746 : Design System > Version 8.3   > Scroll bar alignment issue. by @poojagurav21 in #918 | Design   System > Version 8.3 > Scroll bar alignment issue. · Issue #746 ·   Wai-Technologies/raaghu-react | In progress |   | Nitin | Rameshwar
4 | Resolved Bug 814 : Design System > Version 8.3   > Component > Product list > Product list with Inline price >   small mobile > Not able to see full image. by @nitinsonawane123 in #964 | Design   System > Version 8.3 > Component > Product list > Product list   with Inline price > small mobile > Not able to see full image · Issue   #814 · Wai-Technologies/raaghu-react |   | Ready for Prod | Nitin | Rameshwar
5 | Resolved Bug 806 : Design System > Version 8.3   >Charts > Stacked Chart > Small and large mobile view chart is not   display proper by @poojagurav21 in #952 | Design   System > Version 8.3 >Charts > Stacked Chart > Small and large   mobile view chart is not display proper. · Issue #806 ·   Wai-Technologies/raaghu-react |   | Ready for Prod | Pooja | Rameshwar
6 | Resolved Bug 810 : Component > Datatable > Action   button on Left side > Not able to see the 'Edit' option after hovering   over the row below in the table by @VenuKG in #965 | Design   System > Version 8.3 > Component > Datatable > Action button on   Left side > Not able to see the 'Edit' option after hovering over the row   below in the table · Issue #810 · Wai-Technologies/raaghu-react |   | Ready for Prod | Venu | Rameshwar
7 | Resolved Bug 533 : Storybook> Click on change   the theme of the preview open list select light or dark then list not close.   by @nitinsonawane123 in #1058 | Storybook>   Click on change the theme of the preview open list select light or dark then   list not close. · Issue #533 · Wai-Technologies/raaghu-react |   | Already Closed | Nitin | Rameshwar
8 | Resolved Bug 972 : Components > Small, Large,   Tablet view Save Cancel button alignment issue by @nitinsonawane123 in #1017 | Design   System > Components > Small, Large, Tablet view Save Cancel button   alignment issue. · Issue #972 · Wai-Technologies/raaghu-react |   | Already Closed | Nitin | Rameshwar
9 | Resolved Bug 1052 : Design System > Elements   > Avatar > Default > Dark theme background does not display proper   by @poojagurav21 in #1056 | Design   System > Elements > Avatar > Default > Dark theme background does   not display proper. · Issue #1052 · Wai-Technologies/raaghu-react |   | Ready for Prod | Pooja | Rameshwar
10 | Resolved Bug 1047 : Design System > Components   > Billing > Default > Controls > Add billingData display error   message by @nitinsonawane123 in #1069 | Design   System > Components > Billing > Default > Controls > Add   billingData display error message. · Issue #1047 ·   Wai-Technologies/raaghu-react |   | Already Closed | Nitin | Rameshwar
11 | Resolved Bug 1005 : Design System >   Components> Claims > Default > Plus button alignment issue by @nitinsonawane123 in #1071 | Design   System > Components> Claims > Default > Plus button alignment   issue. · Issue #1005 · Wai-Technologies/raaghu-react |   | Already Closed | Nitin | Rameshwar
12 | Resolved Bug time picker element name change as   per the other element format by @abhijeetjawale1 in #1072 | Design   System > Element > Create new element Time Picker. · Issue #900 ·   Wai-Technologies/raaghu-react |   | Ready for Prod | Abhijeet | Rameshwar
13 | Completed Task 1046 : Design System > Element   > Create new element for Skeleton. by @dhirajlaha in #1064 | Design   System > Element > Create new element for Skeleton. · Issue #1046 ·   Wai-Technologies/raaghu-react |   | Ready for Prod | Dhiraj | Rameshwar
14 | Resolved Bug 1051 : Design System >Accordion   >Default > Dark theme chevron & border is not display proper   by @abhijeetjawale1 in #1063 | Design   System >Accordion >Default > Dark theme chevron & border is not   display proper. · Issue #1051 · Wai-Technologies/raaghu-react |   | Reopen | Abhijeet | Rameshwar



<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='font-size:11.0pt'><o:p>&nbsp;</o:p></span></p>


</body>

</html>
