### ISSUE TITLE
Design System > Check and resolve conflicts for Maps and charts.

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1144]
**Design System > Check and resolve conflicts for Maps and charts.**
1.There are 146 conflicts, which needs to be checked while merging Prasanna's branch into main branch. I will go through each changes.
2.Maps and Charts component has to be checked before merging into main Figma file

**Comment by Prathamesh-UXD** [comment]
I have check all maps and charts. Now assigning this task to Prasanna to make changes in the component.
