### ISSUE TITLE
Bug : Component >Dashboard > Borders are missing for each widget

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#115]
Actual result -

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/f0a8302b-4279-435b-b890-5f8e5f55918a)

Expected result -

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/74b116b1-76e8-4c73-bafb-6ef5dab9e07b)

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/c0d835f1-8e82-4507-bfec-19045ae8b2cd)
