### ISSUE TITLE
Bug : Component > Webhook Subscription >Empty state illustration is missing

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#116]
Actual result - 

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/947d2294-f368-4835-aefe-605a195f13c3)

Expected result -

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/0d4ba9e3-b9b7-4a4e-b9b8-1dd2a6b3a496)

**Comment by rameshwarkamandar** [comment]
Already resolved-
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/84d67f37-8101-4884-9196-158efaac4e51)
