### ISSUE TITLE
Design System -> Build verification - Version 1.1.8.9 received on 3rd Dec

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1205]
Design System -> Build verification - Version 1.1.8.9 received on 3rd Dec

https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8.9(s)

**Comment by RadhikaB123** [comment]
Tested all bugs
https://waii-my.sharepoint.com/:x:/r/personal/triveni_kulkarni_waiin_com/_layouts/15/Doc.aspx?sourcedoc=%7B54CEA316-8532-41EE-847A-F69B81C5F07D%7D&file=[Storybook_Build.xlsx](https://waii-my.sharepoint.com/:x:/r/personal/triveni_kulkarni_waiin_com/_layouts/15/Doc.aspx?sourcedoc=%7B54CEA316-8532-41EE-847A-F69B81C5F07D%7D&file=Storybook_Build.xlsx&wdLOR=c1228B003-DE56-44ED-8F57-855CA2B1EBFD&fromShare=true&action=default&mobileredirect=true&isSPOFile=1&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDExMDExNTcxNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)&wdLOR=c1228B003-DE56-44ED-8F57-855CA2B1EBFD&fromShare=true&action=default&mobileredirect=true&isSPOFile=1&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDExMDExNTcxNiIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D

Added following bugs-

1. https://github.com/Wai-Technologies/raaghu-react/issues/1213
2. Design System > Elements > Datepicker > Default/With time/Advanced > Layout > Minor UI issues · Issue #1215 · Wai-Technologies/raaghu-react
3. Design System > Elements > Accordion > Docs > Background color is showing to the chevron of first accordion · Issue #1216 · Wai-Technologies/raaghu-react
4. Design System > Component > Blog Post > Default > Not able to see last field of form and button size is bigger than field · Issue #1207 · Wai-Technologies/raaghu-react
5. https://github.com/Wai-Technologies/raaghu-react/issues/1208
6. Design System > Side nav bar > Component > Components are not arrange in alphabetically · Issue #1209 · Wai-Technologies/raaghu-react
7. Design System > Tree structure build issues. · Issue #1198 · Wai-Technologies/raaghu-react
8. Design System > Progress bar build issues. · Issue #1199 · Wai-Technologies/raaghu-react
