### ISSUE TITLE
Design System -> Build verification - Dev received on 10th Dec

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1243]
Design System -> Build verification - Dev received on 10th Dec

![Image](https://github.com/user-attachments/assets/42e171dc-a1fa-4f1a-b3e0-2e390e0b49c4)

**Comment by rameshwarkamandar** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bug /Task ID | State | Product | Worked on
-- | -- | -- | -- | -- | --
1 | Design   System > Element > Date Picker changes · Raaghu Design System | 971 | Resolved | Design System | Akshay
3 | Design   System > Components > Calendar > Small mobile view text and   alignment issue. · Raaghu Design System | 991 | Resolved | Design System | Nitin
4 | Design   System > Elements > Button > Default > All story's Height &   Width issue. · Raaghu Design System | 1050 | Resolved | Design System | Nitin
5 | Design   System >Elements > File Uploader > All stories multiple -true upload   file display twice file. · Raaghu Design System | 1090 | Resolved | Design System | Nitin
6 | Design   System > Components > Chat > Default > Placeholder text &   icon is not centralized. · Raaghu Design System | 1107 | Resolved | Design System | Nitin
7 | Design   System > Element or Component > Comment component issue while exporting   it as a reference in another project and has formatting issue · Raaghu Design   System | 1155 | Resolved | Design System | Nitin
8 | Design   System > Element > AI Prompt for new project flow · Raaghu Design   System | 989 | Reopen | Design System | Rahul
9 | Design   System > In Calendar only selected month's date should be visible, rest   can be greyed out · Raaghu Design System | 1195 | Resolved | Design System | Akshay
10 | Design   System > Elements > Datepicker > Default/With time/Advanced >   Layout > Minor UI issues · Raaghu Design System | 1215 | Resolved | Design System | Venu
11 | Design   System > Side nav bar > Component > Components are not arrange in   alphabetically · Raaghu Design System | 1209 | Resolved | Design System | Venu



</body>

</html>
Resolved - 9
 Reopen - 2
