### ISSUE TITLE
Design System -> Build verification - Version 1.1.9.1 received on 13th Dec

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#1278]
Design System -> Build verification - Version 1.1.9.1 received on 13th Dec

**Comment by RadhikaB123** [comment]
![Image](https://github.com/user-attachments/assets/10a01948-8df9-461c-80d1-e92a40fac259)
![Image](https://github.com/user-attachments/assets/ac4a0d8b-a72a-47fd-856a-f7877ef6560d)
![Image](https://github.com/user-attachments/assets/ab5dc645-133f-45c5-8a4e-6bb2c1743c77)

Bug list
![Image](https://github.com/user-attachments/assets/4b44fd41-38f4-485d-b1bb-a76ed59efc93)
