### ISSUE TITLE
Bug : Introduction Page > UI Issues

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#168]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/52011c50-9014-467a-8d3c-3bb24d103748)

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/d0504283-a6fe-4115-ab7d-475b99f43351)

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/01679e3f-9623-4480-b2b3-dced733af3a2)

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/d3fd8e30-f72f-487c-80ba-08eafea8834f)

**Comment by neeraj-bhakre** [comment]
PR merged
