### ISSUE TITLE
Bug : Issues on Component > Data table > Action modal issue

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#258]
Action modal should get closed once click outside the modal and it should open in left side

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/8bf289b0-9292-4c7f-8885-63dc5212a598)

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/6f09bc97-c72b-4bd0-9de1-3647c1d3526f)
