### ISSUE TITLE
Bug : Component > Directory List > Unable to see Component

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#262]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/b25555b1-decc-4c34-a4df-eb7ca38f5e68)

**Comment by AkshayPotphode** [comment]
Issue is already fixed, so closing this bug.

Screenshot :
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155605401/d75092a6-abae-4e7f-89c6-4795fc73f98f)
