### ISSUE TITLE
Bug : Component > Hide Unused components

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#275]
- [x] Code Mirror
- [x] Feature Management
- [x] Forms Questions
- [x] Hierarchy
- [x] Order Details  
- [x] Permission Tree  
- [x] Questions  
- [x] Syntax Highlighter

**Comment by suraj-khupse** [comment]
Check above component is hide or not.

**Comment by rameshwarkamandar** [comment]
Completed -



![Image](https://github.com/user-attachments/assets/10b71f74-616f-4748-a2eb-edd1c295bb40)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni 
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
stage-react.raaghu.ai Not Hide this Component Hierarchy -

![image](https://github.com/user-attachments/assets/af751497-e81e-42a9-a131-44c6543ee28a)

**Comment by rameshwarkamandar** [comment]
Completed.
![image](https://github.com/user-attachments/assets/48dd0327-5b8b-4d5e-86e3-218c182e9b86)
