### ISSUE TITLE
Bug : Component > Profile edit > Image is missing

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#307]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/80bf3aed-71ce-43ed-9235-02813a044265)

**Comment by rameshwarkamandar** [comment]
Issue is not resolve Image is not display deployed site

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/f82268a6-d0c7-4ae6-a047-688f87f5ba54)

**Comment by rameshwarkamandar** [comment]
Completed - 



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/a7e5635b-2e43-4212-9faa-21b47fc5b555)
