### ISSUE TITLE
Component > Moving Portal Components to Storybook

### ISSUE THREAD

**Issue by Ketan-Khalate** [Wai-Technologies/raaghu-react#377]
List of Components to be Moved -
1) Add Member
2) Assistance
3) Register Member
4) Copy Text
5) Get Assistance
6) Invoice Detail Receipt
7) Order Confirmation
8) Payment Card
9) Premium Support
10) Purchase Developer Seats

**Comment by trivenikulkarni** [comment]
Already in closed status, so closing it
