### ISSUE TITLE
Elements > Modal> Screen fading issue

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#382]
Storybook Modal Elements - 

Once click on Default button and go to other components screen gets fade.

**Screenshot**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/19ec9f1f-a8b8-4c3c-a80e-27cc9ae2c59e)

**Comment by AkshayPotphode** [comment]
As discussed with @Ketan-Khalate , this task need to work on future sprint for storybook.

**Comment by trivenikulkarni** [comment]
Storybook limitation so cannot fix this

**Comment by rameshwarkamandar** [comment]
Fixed

<img width="1920" height="1003" alt="Image" src="https://github.com/user-attachments/assets/bf9e2de5-7e78-4fa4-aff2-93882da913e7" />
