### ISSUE TITLE
Task > Create Loader Element

### ISSUE THREAD

**Issue by Ketan-Khalate** [Wai-Technologies/raaghu-react#393]

**Comment by rameshwarkamandar** [comment]
Completed-
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/b4393308-76fd-4554-8ff1-a256adce5eb9)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/040e3eeb-b7e3-4081-a48d-002b376a7f4e)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/e8ea6d97-2ca3-4506-8e7d-2288f887314f)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/4082e40a-86ae-4f44-ae7a-83a4d3206cc9)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/069b132d-9401-4e41-88b3-f6f3aa1c5039)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/f3edff5f-343c-4c30-a486-6b0d0cb4be5a)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/5ea233d8-6068-435d-9739-c72fb07c681b)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/7cd74cc9-6355-4165-ad85-072afb2e36ed)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/0aa9bd0c-02bf-4cc7-ab4f-7fa9e0150000)
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/24d27d44-0599-413b-9fec-625f76f3c39e)
