### ISSUE TITLE
Components > Api scope resource > Button alignment issue

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#401]
While going through the application process, found following issue,

## Actual Result:

> Api scope resource button alignment issue.

## Screenshot:

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/b4284353-4dce-4c96-93bd-806f381953d1)

**Comment by AkshayPotphode** [comment]
There were three similar components, Api Scope Resource, Claim & Client Resource. Out of that Api Scope Resource & Client Resource are Hide.

**Comment by trivenikulkarni** [comment]
This issue is from hidden component , so closing this bug.
