### ISSUE TITLE
Elements > Video Player > autoplay is true but video is not playing

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#402]
While going through the application process, found following issue,

## Actual Result:

Video Player autoplay is true but video is not playing.

## Screenshot:

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/fa9068e9-e8d5-40b2-ab88-fba966d9d344)

**Comment by AkshayPotphode** [comment]
When video gets completed then it gets auto play, so it is working as per the requirement.

**Comment by trivenikulkarni** [comment]
It is as per the functionality, so closing the bug

**Comment by trivenikulkarni** [comment]
It is as per the functionality, so closing the bug
