### ISSUE TITLE
Components > Client Resource > After submitting unable to save client resource details, Data is not shown in action

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#407]
While going through the application process, found following issue,

## Actual Result:

After submitting unable to save client resource details, Data is not shown in action.

## Screenshot:

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/df3de35e-de70-4e48-aa43-98eb89fad4bf)

**Comment by AkshayPotphode** [comment]
There were three similar components, Api Scope Resource, Claim & Client Resource. Out of that Api Scope Resource & Client Resource are Hide.

**Comment by trivenikulkarni** [comment]
Same as <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">



--




</body>

</html>
[Components > Api scope resource > Button alignment issue · Issue #401 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/401) so clsing this bug

**Comment by trivenikulkarni** [comment]
same as 401
