### ISSUE TITLE
Portal : Issues regarding subscriber dashboard

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#412]
**Describe the bug**
1.Icons are not clickable but still has hand cursor
2.Title is repeated in description
3.In note sentence, It should in "developer" instead of "developers"
4.Out of 4 dashboards, only one sentence as full stop

**Pre- Requisites**
Login to https://dev.raaghu.io/

**Steps to reproduce the behavior:**
Go to Dashboard section of landing page of portal
Verify the cursor for icons in dashboard
Scroll down and check the description of each section

**Actual behavior**
1.Icons are not clickable but still has hand cursor
2.Title is repeated in description
3.In note sentence, It should in "developer" instead of "developers"
4.Out of 4 dashboards, only one sentence as full stop

**Expected behavior**
1.Icons are not clickable so it should not have hand cursor
2.Repeated  Title in description should be removed
3.In note sentence, It should in "developer" instead of "developers"
4.Full stop is not required for these sentence

**Screenshots**
![Subscriber_Dashboard](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/be8561db-633b-4f75-a36c-d7bf3af96d14)
![Subscriber_Dashboard_TextCorrections](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/48404e12-f1c7-4de4-b866-66e50a2e5152)
![Subscriber_Dashboard_Fullstop](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/73cee805-d4dc-4373-b933-19529b8218af)

**Desktop** (please complete the following information):
OS: Windows
Browser chrome
Smartphone (please complete the following information): : NA

Version [125]

**Additional context**
NA

@kaushikgokhale

**Comment by rameshwarkamandar** [comment]
Completed - 

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/02da6c6b-1a55-4293-ad50-9e197eef816c)



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/d3505f95-d8eb-4251-b05d-53e6fe973347)
