### ISSUE TITLE
Portal : Placeholder of search textbox not matching to search feature implementation

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#413]
**Describe the bug**
Placeholder of search textbox not matching to search feature implementation

**Pre-requisites**
Login to https://dev.raaghu.io

**Steps to reproduce the behavior:**
1. Go to User grid section on landing page
2. Verify the placeholder for search textbox

**Actual behavior**
Placeholder of search textbox not matching to search feature implementation

**Expected behavior**
1.If placeholder is "Search" , it should be global search, but currently only user name is getting searched.
so either placeholder needs to make specific like Search By Username
or if we keep the placeholder "Search" , need to implement global search.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [e.g. chrome]
 - Version [125]

**Smartphone (please complete the following information):**  : NA

**Additional context**
NA

@kaushikgokhale

**Comment by Ketan-Khalate** [comment]
Hello @trivenikulkarni  we need backend changes for filters as we want to filter all fields for member-list grid.

**Comment by trivenikulkarni** [comment]
@pravinwaghmare23  please check what is pending for this task and take this task ahead.

**Comment by pravinwaghmare23** [comment]
Global search is implemented so keeping search placeholder as  search
![Image](https://github.com/user-attachments/assets/4dc0bf6a-830e-42ec-944c-724fffa4f0d0)

**Comment by rameshwarkamandar** [comment]
Full name is not search -

![Image](https://github.com/user-attachments/assets/c6cb0345-d9d9-4c22-add2-727667a42cfa)

![Image](https://github.com/user-attachments/assets/0cd45adb-f861-47ba-8a41-2c8a9ae49fb0)

**Comment by rameshwarkamandar** [comment]
Completed - Search filter is working.

![Image](https://github.com/user-attachments/assets/ffe985f6-445b-436c-ab7c-2eac296c77f7)

![Image](https://github.com/user-attachments/assets/9463bc20-499b-46a1-a22c-28acddc18692)

![Image](https://github.com/user-attachments/assets/0ace6b5f-c200-4500-bda7-97a3caada25a)

![Image](https://github.com/user-attachments/assets/c5db5c99-adb5-4273-ac54-38679996d8a2)
