### ISSUE TITLE
Storybook > Component > User Delegations > Default > After submitting End date start date is not display in action

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#417]
**Describe the bug**
After submitting End date start date is not display is action.

**Pre- Requisites**
Login to https://react.raaghu.io/

**To Reproduce**
1. Go to 'Components'
2. Click on 'User Delegations '
3. Click on Default
4.  Click on 'Delegate new user  

**Expected behavior**
After submitting End date start date is displayed in action.

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/f315056a-2b10-41fb-b827-152d5ff49385).

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by AkshayPotphode** [comment]
As discussed with @Ketan-Khalate , this task need to work on future sprint for storybook.

**Comment by rameshwarkamandar** [comment]
Completed -


![Image](https://github.com/user-attachments/assets/d231ff8f-970e-4f7e-9071-aac3d4c5b7ad)

**Comment by rameshwarkamandar** [comment]
**Version 1.1.7**
![image](https://github.com/user-attachments/assets/20b898fa-d1f7-40ed-ba51-3093196c0427)
