### ISSUE TITLE
Storybook > Components >Identity Ldap Management> Default > Spacing issue

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#435]
**Describe the bug**
1. Username spacing issue.

**To Reproduce**
Go to 'Components'
Click on 'Identity Ldap Management'
Click on 'Default'

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/4881e9a6-ce8b-4fe9-b066-478b52bbb725)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by AkshayPotphode** [comment]
This Bug is resolved in https://github.com/Wai-Technologies/raaghu-react/pull/439.

**Comment by rameshwarkamandar** [comment]
Completed -

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/62341fac-f056-4743-8003-d790300985cf)
