### ISSUE TITLE
Storybook > Bug retesting of Resolved bugs

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#457]
**Description**
Bug retesting of Resolved bugs.

**Comment by trivenikulkarni** [comment]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/f0acb511-f099-4b3b-a62e-b5ecc9356971)



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/77a705ae-5249-46fa-9e1f-959e692f7264)

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Task ID | Bug Title | Status | Remark |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
1 | 316 | Bug :   Component > Integration > After clicking on View integration blank page   displayed · Issue #316 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
2 | 327 | Bug :   Component > Benefit > Card alignment issue · Issue #327 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
2 | 164 | Bug: User   Basic- Add "Save" and "Cancel" button and spacing is   expected between two words (Email Address, Phone Number etc) · Issue #164 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
3 | 257 | Bug :   Issues on Components > Save and Cancel button spacing is expected to same   as other fields · Issue #257 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
4 | 246 | Bug :   Issues on Component > Application work flows · Issue #246 ·   Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
5 | 230 | https://github.com/Wai-Technologies/raaghu-react/issues/230 | Closed | Already closed. |   |   |  
6 | 263 | Bug :   Component > Dynamic entity property > Parameters displaying twice ·   Issue #263 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
7 | 278 | Bug :   Component > Permission tree > Nodes are missing · Issue #278 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
8 | 343 | Bug >   Tenant Management > Placeholder is missing · Issue #343 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
9 | 344 | Bug >   Tenant Register > Chevron are not visible · Issue #344 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
10 | 352 | Bug :   Component > Tenant Information > Form field is not getting clear ·   Issue #352 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
11 | 346 | Bug :   Component > Payment tenure > Text is expected in center of the fields ·   Issue #346 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
12 | 350 | Bug :   Component >New language > Hand cursor is expected for dropdowns/Select   list · Issue #350 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
13 | 345 | Bug :   Component > Shopping car > By default value is expected · Issue #345 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
14 | 348 | Bug :   Component > Reduce buttons sizes of all the components · Issue #348 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
15 | 362 | Bug >   Components >Billing > Download icon alignment issue · Issue #362 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
16 | 364 | Component   > OTP Input Field with Dynamic Inputs and 2 Shapes (Square and Circle) ·   Issue #364 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
17 | 365 | Components   > Login > After Submitting field is not clear · Issue #365 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
18 | 368 | Components   >Api scope resource > After submitting, data is not display in action ·   Issue #368 · Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
19 | 307 | Bug :   Component > Profile edit > Image is missing · Issue #307 ·   Wai-Technologies/raaghu-react (github.com) | Reopen |   |   |   |  
20 | 349 | Bug :   Component > Page not found > Raaghu logo is missing · Issue #349 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
21 | 377 | Component   > Moving Portal Components to Storybook · Issue #377 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
22 | 379 | Issues ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
23 | 390 | Bug :   Build Issue for Version 1.1.3 · Issue #390 · Wai-Technologies/raaghu-react   (github.com) | Closed | Already closed. |   |   |  
24 | 388 | Components>   Edition Information> Alignment issue counter · Issue #388 ·   Wai-Technologies/raaghu-react (github.com) | Closed | Already closed. |   |   |  
25 | 393 | Task >   Create Loader Element · Issue #393 · Wai-Technologies/raaghu-react   (github.com) | Closed |   |   |   |  
26 | 396 | Elements   > Checkbox Group >In control state select Error Checkbox spacing issue   · Issue #396 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
27 | 397 | Element   > Datepicker > Default & With Time one corner is not rounded ·   Issue #397 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
28 | 398 | Elements   > Avtar > With profile > size small and medium only one is working.   · Issue #398 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
29 | 399 | Elements   > Toggle > When change size small true then sun icon is not visible ·   Issue #399 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
30 | 403 | Components   > Api resource basic > Ui label name and action data name are different   · Issue #403 · Wai-Technologies/raaghu-react (github.com) | Reopen |   |   |   |  
31 | 405 | Components   > Apply for position > After submitting uploaded file is not clear ·   Issue #405 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
32 | 406 | Components   > Change password > New Password & New Password Confirm both are   not same · Issue #406 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
33 | 408 | Components   > Feeds > Docs are missing · Issue #408 · Wai-Technologies/raaghu-react   (github.com) | Closed |   |   |   |  
34 | 410 | Components   > Email setting > New and confirm email are not same · Issue #410 ·   Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
35 | 414 | Storybook   > Component > Get Assistance > Default > Able to submit incorrect   email id · Issue #414 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
36 | 415 | Storybook   > Component > Identity management > Default > Form content is   hidden · Issue #415 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
37 | 416 | Storybook   > Component > Invoice Detail Receipt > Default > WAI logo is not   display · Issue #416 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
38 | 418 | Storybook   > Component >Payment Card > Default > Invalid placeholder · Issue   #418 · Wai-Technologies/raaghu-react (github.com) | Closed |   |   |   |  
39 | 420 | https://github.com/Wai-Technologies/raaghu-react/issues/420 | Closed |   |   |   |  
40 | 421 | Storybook   > Component >New Language > Default > After submitting Display   Name placeholder is not display · Issue #421 · Wai-Technologies/raaghu-react   (github.com) | Closed |   |   |   |  
41 | 422 | Storybook   > Component >Identity Oauth Management > Default > ClientId,   ClientSecret Spacing issues · Issue #422 · Wai-Technologies/raaghu-react   (github.com) | Closed |   |   |   |  
42 | 423 | Storybook   > Component >Benefit > Default > In Default when selecting dark   theme card title is not display · Issue #423 · Wai-Technologies/raaghu-react   (github.com) | Closed |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  
  |   |   |   |   |   |   |  



</body>

</html>
Sr.No	Task ID	Bug Title	Status	Remark			
1	316	[Bug : Component > Integration > After clicking on View integration blank page displayed · Issue #316 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/316)	Closed	Already closed.			
2	327	[Bug : Component > Benefit > Card alignment issue · Issue #327 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/327)	Closed	Already closed.			
2	164	[Bug: User Basic- Add "Save" and "Cancel" button and spacing is expected between two words (Email Address, Phone Number etc) · Issue #164 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/164)	Closed	Already closed.			
3	257	[Bug : Issues on Components > Save and Cancel button spacing is expected to same as other fields · Issue #257 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/257)	Closed	Already closed.			
4	246	[Bug : Issues on Component > Application work flows · Issue #246 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/246)	Closed				
5	230	https://github.com/Wai-Technologies/raaghu-react/issues/230	Closed	Already closed.			
6	263	[Bug : Component > Dynamic entity property > Parameters displaying twice · Issue #263 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/263)	Closed	Already closed.			
7	278	[Bug : Component > Permission tree > Nodes are missing · Issue #278 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/278)	Closed	Already closed.			
8	343	[Bug > Tenant Management > Placeholder is missing · Issue #343 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/343)	Closed	Already closed.			
9	344	[Bug > Tenant Register > Chevron are not visible · Issue #344 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/344)	Closed	Already closed.			
10	352	[Bug : Component > Tenant Information > Form field is not getting clear · Issue #352 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/352)	Closed	Already closed.			
11	346	[Bug : Component > Payment tenure > Text is expected in center of the fields · Issue #346 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/346)	Closed	Already closed.			
12	350	[Bug : Component >New language > Hand cursor is expected for dropdowns/Select list · Issue #350 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/350)	Closed	Already closed.			
13	345	[Bug : Component > Shopping car > By default value is expected · Issue #345 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/345)	Closed	Already closed.			
14	348	[Bug : Component > Reduce buttons sizes of all the components · Issue #348 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/348)	Closed	Already closed.			
15	362	[Bug > Components >Billing > Download icon alignment issue · Issue #362 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/362)	Closed	Already closed.			
16	364	[Component > OTP Input Field with Dynamic Inputs and 2 Shapes (Square and Circle) · Issue #364 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/364)	Closed	Already closed.			
17	365	[Components > Login > After Submitting field is not clear · Issue #365 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/365)	Closed	Already closed.			
18	368	[Components >Api scope resource > After submitting, data is not display in action · Issue #368 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/368)	Closed	Already closed.			
19	307	[Bug : Component > Profile edit > Image is missing · Issue #307 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/307)	Reopen				
20	349	[Bug : Component > Page not found > Raaghu logo is missing · Issue #349 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/349)	Closed	Already closed.			
21	377	[Component > Moving Portal Components to Storybook · Issue #377 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/377)	Closed	Already closed.			
22	379	[Issues · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/379)	Closed	Already closed.			
23	390	[Bug : Build Issue for Version 1.1.3 · Issue #390 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/390)	Closed	Already closed.			
24	388	[Components> Edition Information> Alignment issue counter · Issue #388 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/388)	Closed	Already closed.			
25	393	[Task > Create Loader Element · Issue #393 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/393)	Closed				
26	396	[Elements > Checkbox Group >In control state select Error Checkbox spacing issue · Issue #396 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/396)	Closed				
27	397	[Element > Datepicker > Default & With Time one corner is not rounded · Issue #397 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/397)	Closed				
28	398	[Elements > Avtar > With profile > size small and medium only one is working. · Issue #398 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/398)	Closed				
29	399	[Elements > Toggle > When change size small true then sun icon is not visible · Issue #399 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/399)	Closed				
30	403	[Components > Api resource basic > Ui label name and action data name are different · Issue #403 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/403)	Reopen				
31	405	[Components > Apply for position > After submitting uploaded file is not clear · Issue #405 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/405)	Closed				
32	406	[Components > Change password > New Password & New Password Confirm both are not same · Issue #406 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/406)	Closed				
33	408	[Components > Feeds > Docs are missing · Issue #408 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/408)	Closed				
34	410	[Components > Email setting > New and confirm email are not same · Issue #410 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/410)	Closed				
35	414	[Storybook > Component > Get Assistance > Default > Able to submit incorrect email id · Issue #414 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/414)	Closed				
36	415	[Storybook > Component > Identity management > Default > Form content is hidden · Issue #415 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/415)	Closed				
37	416	[Storybook > Component > Invoice Detail Receipt > Default > WAI logo is not display · Issue #416 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/416)	Closed				
38	418	[Storybook > Component >Payment Card > Default > Invalid placeholder · Issue #418 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/418)	Closed				
39	420	https://github.com/Wai-Technologies/raaghu-react/issues/420	Closed				
40	421	[Storybook > Component >New Language > Default > After submitting Display Name placeholder is not display · Issue #421 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/421)	Closed				
41	422	[Storybook > Component >Identity Oauth Management > Default > ClientId, ClientSecret Spacing issues · Issue #422 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/422)	Closed				
42	423	[Storybook > Component >Benefit > Default > In Default when selecting dark theme card title is not display · Issue #423 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/423)	Closed

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Task ID | Bug Title | Status
-- | -- | -- | --
1 | 424 | Storybook   > Component >Change User Password > Default >All Password field   eye icon is missing · Issue #424 · Wai-Technologies/raaghu-react (github.com) | Closed
2 | 425 | Storybook   > Components >CMS > Default >Email address validation is   incorrect · Issue #425 · Wai-Technologies/raaghu-react (github.com) | Closed
3 | 430 | Storybook   > Components > Correct components name and spacing issue · Issue #430 ·   Wai-Technologies/raaghu-react (github.com) | Closed
4 | 434 | Storybook   > Components >Identity Client Basic > Default > When Small &   large Mobile label is sticking inputbox · Issue #434 ·   Wai-Technologies/raaghu-react (github.com) | Closed
5 | 435 | Storybook   > Components >Identity Ldap Management> Default > Spacing issue ·   Issue #435 · Wai-Technologies/raaghu-react (github.com) | Closed
6 | 431 | Storybook   > Components > Email Settings New and Email Settings Create one   component · Issue #431 · Wai-Technologies/raaghu-react (github.com) | Closed
7 | 436 | Storybook   > Components >Integration > Default > Selecting the dark theme   Notion and GitHub logos are not displayed. · Issue #436 ·   Wai-Technologies/raaghu-react | Reopen
8 | 437 | Storybook   > Components >Features New > Default >Restore to Default and Save   buttons are not working. · Issue #437 · Wai-Technologies/raaghu-react   (github.com) | Reopen
9 | 440 | https://github.com/Wai-Technologies/raaghu-react/issues/440 | Closed
10 | 441 | Storybook   > Components >Product List > Product List with Inline Price >Up   word side corner issue. · Issue #441 · Wai-Technologies/raaghu-react   (github.com) | Closed
11 | 442 | Storybook   > Components >Properties > Default > Select small mobile view   overlap buttons · Issue #442 · Wai-Technologies/raaghu-react (github.com) | Closed
12 | 443 | Storybook   > Components >User Basics > Default > Email validation is not   correct Username label placeholder issue · Issue #443 ·   Wai-Technologies/raaghu-react (github.com) | Closed
13 | 444 | Storybook   > Components >Teams > Default > Small mobile view image is not   display centered. · Issue #444 · Wai-Technologies/raaghu-react (github.com) | Closed
14 | 445 | Storybook   > Components >Secrets> Default > Invalid placeholder · Issue #445   · Wai-Technologies/raaghu-react (github.com) | Closed
15 | 446 | Storybook   > Components >Register > Default >Labels are missing. · Issue   #446 · Wai-Technologies/raaghu-react (github.com) | Closed
16 |   |   |  
  |   |   |  



</body>

</html>
Sr.No	Task ID	Bug Title	Status
1	424	[Storybook > Component >Change User Password > Default >All Password field eye icon is missing · Issue #424 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/424)	Closed
2	425	[Storybook > Components >CMS > Default >Email address validation is incorrect · Issue #425 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/425)	Closed
3	430	[Storybook > Components > Correct components name and spacing issue · Issue #430 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/430)	Closed
4	434	[Storybook > Components >Identity Client Basic > Default > When Small & large Mobile label is sticking inputbox · Issue #434 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/434)	Closed
5	435	[Storybook > Components >Identity Ldap Management> Default > Spacing issue · Issue #435 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/435)	Closed
6	431	[Storybook > Components > Email Settings New and Email Settings Create one component · Issue #431 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/431)	Closed
7	436	[Storybook > Components >Integration > Default > Selecting the dark theme Notion and GitHub logos are not displayed. · Issue #436 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/436)	Reopen
8	437	[Storybook > Components >Features New > Default >Restore to Default and Save buttons are not working. · Issue #437 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/437)	Reopen
9	440	https://github.com/Wai-Technologies/raaghu-react/issues/440	Closed
10	441	[Storybook > Components >Product List > Product List with Inline Price >Up word side corner issue. · Issue #441 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/441)	Closed
11	442	[Storybook > Components >Properties > Default > Select small mobile view overlap buttons · Issue #442 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/442)	Closed
12	443	[Storybook > Components >User Basics > Default > Email validation is not correct Username label placeholder issue · Issue #443 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/443)	Closed
13	444	[Storybook > Components >Teams > Default > Small mobile view image is not display centered. · Issue #444 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/444)	Closed
14	445	[Storybook > Components >Secrets> Default > Invalid placeholder · Issue #445 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/445)	Closed
15	446	[Storybook > Components >Register > Default >Labels are missing. · Issue #446 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/446)	Closed
16

**Comment by rameshwarkamandar** [comment]
Completed retesting of 57 storybook bugs
Reopen bugs: 4
Already Closed bug: 23
Closed bug: 30

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


17 | 450 | Storybook   > Components >Billing Address > Default > Enter a value, remove a   value, and then click on the next field to see two error messages. · Issue   #450 · Wai-Technologies/raaghu-react (github.com) | Closed |   | 04-07-2024
-- | -- | -- | -- | -- | --




</body>

</html>
17	450	[Storybook > Components >Billing Address > Default > Enter a value, remove a value, and then click on the next field to see two error messages. · Issue #450 · Wai-Technologies/raaghu-react (github.com)](https://github.com/Wai-Technologies/raaghu-react/issues/450)	Closed		04-07-2024



Completed retesting of 58 storybook bugs
Reopen bugs: 4
Already Closed bug: 23
Closed bug: 31
