### ISSUE TITLE
Storybook > Alert Popup \ Docs : Unable to see the fields properly

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#458]
**Steps to reproduce**
2. 1. Open raaghu design system [Storybook] https://react.raaghu.io/
3. Navigate to  Components\ Alert Popup \ Docs 
4. Click on Alert Popup

**Actual Result** 
Unable to see the fields properly

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/fd68c5e0-834e-434b-bdc4-70133892a86e)

**Expected Result** 
No any field should be cut or grey out. It should be displayed properly

**Comment by trivenikulkarni** [comment]
@akhilShaji1995  
Please add in comment why this was kept on hold and change the status accordingly

@Ketan-Khalate

**Comment by kaushikgokhale** [comment]
Not needed as it is Storybook Docs issue

**Comment by trivenikulkarni** [comment]
Closing issue due to limitation of storybook Doc issue
