### ISSUE TITLE
DS > Implement Changes to Urls through application for Updated Urls

### ISSUE THREAD

**Issue by kaushikgokhale** [Wai-Technologies/raaghu-react#469]
### Implement changes to Urls throughout files as follows,

react.raaghu.io ---> react.raaghu.ai
docs.raaghu.io ---> docs.raaghu.ai
angular.raaghu.io ---> angular.raaghu.ai

**Comment by rameshwarkamandar** [comment]
Completed - 



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/980fe2c2-7c26-4fef-abf4-60fd24aad7fe)



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/35255a4d-3b33-4f4f-a9a0-7b1fb6f8af5d)



![Image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/02b71c38-e81f-47f1-b083-a7e261660247)
