### ISSUE TITLE
Elements >Notification> Selecting dark theme button text is not display.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#470]
**Describe the bug**
1. Notification> Default > Selecting dark theme button text is not display.
2. Size >With Description> Selecting dark theme card text is not display.
3. Widget Portal > Default >Selecting dark theme button text is not display.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Notification'
3. Click on 'Default'

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/276f3010-cf6f-42a5-8f35-dc50d3448190)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/70703648-ff87-41ae-852c-d7df59f0608a)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/a31c4cbd-4721-4830-b8cb-3b76ea847fc7)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed - 
![image](https://github.com/user-attachments/assets/6f57efa0-ea1d-4099-b89c-db4dac5178dc)

![image](https://github.com/user-attachments/assets/aef9787a-9208-4997-8e69-c9007ad77ba1)

![image](https://github.com/user-attachments/assets/ef045e7e-f832-4cd3-9825-ccc41f6036ea)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni 
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
**Version 1.1.7**

![image](https://github.com/user-attachments/assets/1e484e8a-a350-491c-937d-b9079826f6bd)

![image](https://github.com/user-attachments/assets/0b50bdbf-bf0c-4da7-a882-7f47278bb2ec)

![image](https://github.com/user-attachments/assets/49b025a2-4f74-4d91-8d73-547b6e8e6492)
