### ISSUE TITLE
Add newly designed and existing updated components from A. S

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#472]
![image](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/0e207d8f-0c78-4649-b2f3-b83e30658ff3)
@AkshayPotphode  please connect to @neeraj-bhakre for more details

**Comment by rameshwarkamandar** [comment]
Alignment issue -



![image](https://github.com/user-attachments/assets/9ff6fdab-ecb0-438d-9113-15b7989e2557)

**Comment by rameshwarkamandar** [comment]
https://stage-react.raaghu.ai/
@AkshayPotphode "Issue still exists on Staging"

![image](https://github.com/user-attachments/assets/a0c3fa46-a654-449a-8a04-771c2ce7d6bf)

**Comment by rameshwarkamandar** [comment]
Completed -
![image](https://github.com/user-attachments/assets/7c599a7a-b9aa-4b23-8def-549c9271efa7)
