### ISSUE TITLE
Add newly designed and existing updated Layout from Abel Systems

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#475]
Add newly designed and existing updated components from Abel Systems
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Category | Newly Added | Updated Existing
-- | -- | --
Layouts | 1.   Board |  
  | 2.   Highlight |  

</body>

</html>

Please connect to @neeraj-bhakre

**Comment by trivenikulkarni** [comment]
Shivani has started on this task so changing allocation from Pravin to Shivani

**Comment by rameshwarkamandar** [comment]
Completed -
![image](https://github.com/user-attachments/assets/5c1d6a4a-e9b4-4ed3-b1c4-a70e450e94e7)

![image](https://github.com/user-attachments/assets/60062cbe-b1b2-4e84-9229-278f5af66cd3)

**Comment by shivani-bhalerao** [comment]
@trivenikulkarni 
"Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7."

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/user-attachments/assets/2df7375d-67cd-4fab-87d9-ce161d25925c)

![image](https://github.com/user-attachments/assets/4476c359-2f90-45eb-94ba-adb011fdbc9b)
