### ISSUE TITLE
Implement Top Navigation With Search

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#478]
Top Navigation With Search

**Comment by rameshwarkamandar** [comment]
Completed - 

![Image](https://github.com/user-attachments/assets/3fb7b0d7-ad9d-4573-b5f9-52b5171d53ba)

**Comment by shivani-bhalerao** [comment]
@trivenikulkarni 
"Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7."

**Comment by rameshwarkamandar** [comment]
![image](https://github.com/user-attachments/assets/1d6319ca-1027-4851-a68b-c3c4ee2d2a25)
