### ISSUE TITLE
Build verification : Storybook  Version 1.1.5 received on 8th July 2024

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#479]
![Image](https://github.com/Wai-Technologies/raaghu-react/assets/135837216/18512f75-1d7f-4675-afa5-33dc97322798)

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Task ID | Bug Title | Status | Remark
-- | -- | -- | -- | --
1 | 400 | Storybook   > Check scrollbar position in storybook It is not right aligned properly ·   Raaghu Design System Storybook - React (github.com) | Closed |  
2 | 438 | Storybook   > Components >Organization Tree> Default > Three dots button   isn't clickable. · Raaghu Design System Storybook - React (github.com) | Closed |  
3 | 449 | Storybook   > Components >Alert Popup > Default > When click on Alert Popup   button and go to next component is not working. · Raaghu Design System   Storybook - React (github.com) | Closed |  
4 | 452 | Storybook   > Components >Dynamic Entity Properties > Default >Placeholder   select entity select parameter is required · Raaghu Design System Storybook -   React (github.com) | Closed |  
5 | 460 | Storybook   > Components >Premium Support > Default >Unable to see images. ·   Raaghu Design System Storybook - React (github.com) | Closed |  
6 | 463 | Storybook   > Elements >Color Picker> Default >Selecting small, large mobile   view Border issue. · Raaghu Design System Storybook - React (github.com) | Closed |  
7 | 464 | Storybook   > Elements>Navbar > Default >Selecting dark theme navbar content   is not display · Raaghu Design System Storybook - React (github.com) | Closed |  
8 | 466 | Components   > File Uploader > After submitting uploaded file is not clear. · Raaghu   Design System Storybook - React (github.com) | Closed |  
9 | 403 | Components   > Api resource basic > Ui label name and action data name are different   · Raaghu Design System Storybook - React (github.com) | Closed |  
10 | 307 | Bug   : Component > Profile edit > Image is missing · Raaghu Design System   Storybook - React (github.com) | Closed |  
11 | 419 | Storybook   > Component >Order Confirmation> Default > Video is not display ·   Raaghu Design System Storybook - React (github.com) | Closed |  
12 | 436 | Storybook   > Components >Integration > Default > Selecting the dark theme   Notion and GitHub logos are not displayed. · Raaghu Design System Storybook -   React | Closed |  
13 | 437 | Storybook   > Components >Features New > Default >Restore to Default and Save   buttons are not working. · Raaghu Design System Storybook - React   (github.com) | Closed |  
14 | 465 | Storybook   > Elements>Button Group> Default >Selecting color Variant light   text is not display. · Raaghu Design System Storybook - React (github.com) | Closed |  
15 | 469 | DS   > Implement Changes to Urls through application for Updated Urls · Raaghu   Design System Storybook - React (github.com) | Closed |  
16 | 429 | Storybook   > Components >Download Collection> Default > After click on   download icon no data display in action · Raaghu Design System Storybook -   React (github.com) | Reopen |  
17 | 448 | Storybook   > Components >Visual Setting > Default >Alignment issue   Subheader, Menu, Footer, click on dropdown chevron is not upward and downward   · Raaghu Design System Storybook - React (github.com) | Reopen |  



</body>

</html>

**Comment by rameshwarkamandar** [comment]
Total Bugs Tested :17
Closed Bug: 15
Reopened Bug: 2
