### ISSUE TITLE
Storybook > Elements >Card Detail >Selecting small mobile view radio button is stick on card text.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#481]
**Describe the bug**
1. Selecting small mobile view radio button is stick on card text.
2. Elements> Avatar >With Initial >Selecting dark theme Initial latter is not display.
3. Elements> Avatar >With Label>Selecting dark theme label is not display proper.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Card Detail'
5. Click on 'Card Detail'

**Expected behavior**
Selecting small mobile view space between card text and radio button.
Selecting dark theme Initial latter is display like WT.
**Screenshots**
Card Detail -
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/1ed3cd55-8a41-4aa6-8cbf-e7ed3c1ff62f)

Avatar -
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/40bcfe07-e92b-4deb-83a7-a28d55e3e39e)

Avatar >With Label -
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/d1bf7f6b-bee8-4877-a320-4f597b95d632)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed -

![Image](https://github.com/user-attachments/assets/0aed900d-9a4b-4ab8-aa00-541e8f4d3f6f)



![Image](https://github.com/user-attachments/assets/7411387a-7f91-4692-a159-d7c4510cb60f)



![Image](https://github.com/user-attachments/assets/71f7bbcf-a4df-4125-b93d-f1b12d989893)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni 
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
**version 1.1.7**
![image](https://github.com/user-attachments/assets/e3dceb5f-af9a-4390-aa83-4128f7d95188)

![image](https://github.com/user-attachments/assets/e9ec7610-1d9a-4cfd-8e26-b03fde06cf20)

![image](https://github.com/user-attachments/assets/7e1ad3e8-c872-4e7e-8f14-6899979fcf65)
