### ISSUE TITLE
Storybook > Elements >Product Image >Column Layout> Alignment Issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#489]
**Describe the bug**
1.  Elements >Product Image >Column Layout>Light theme Alignment Issue.
2.  Elements >Product Image >Column Layout>Selecting dark theme Alignment Issue.
3. Also check small, large mobile view.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Product Image'
4. Click on 'Column Layout'

**Screenshots**
Light Theme
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/480dcfea-3518-4acd-abde-34857c454dc0)

Dark Theme
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/5fa1a97c-070a-46cd-b6de-7a7652b4f3ac)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed -



![Image](https://github.com/user-attachments/assets/4250dbfc-ea02-482c-ab37-9c178ce1dd4c)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
Issue still exists on Staging version 1.1.7

![image](https://github.com/user-attachments/assets/e9d5a77e-ae1c-418c-a728-df796454a4e4)

**Comment by rameshwarkamandar** [comment]
Completed -

![image](https://github.com/user-attachments/assets/05a11031-1d11-48dc-af6a-ecd1ee83efed)
