### ISSUE TITLE
Storybook > Elements >Stat>Default>Dark theme Icon color is not change

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#496]
**Describe the bug**
1. Stat>Default>Dark theme Icon color is not change.
2. Team Member - Two star spacing is require.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Stat'
5. Click on 'Default'

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/f3e6da1a-2b42-4ccc-a6a5-3d33e6b08d10)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/538f8ffc-6502-4352-a2dd-799e8795a310)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed-
![image](https://github.com/user-attachments/assets/77859db5-b8c7-4038-aece-e0063644d3aa)
![image](https://github.com/user-attachments/assets/b0ecdad4-98e2-4da0-a164-5c678e4c3f06)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
**version 1.1.7**
![image](https://github.com/user-attachments/assets/d792a9e3-592d-4315-a084-7fd9bcf4f91d)

![image](https://github.com/user-attachments/assets/b0cd0cf1-5f9f-4ae9-89d2-87c3db3dc2a5)
