### ISSUE TITLE
Storybook > Elements >Toast>Toast without header>Cross icon alignment issue

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#497]
**Describe the bug**
1.Toast>Toast without header>Cross icon alignment issue.

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Toast'
5. Click on 'Toast without header'

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/5b14aca5-d9f9-459a-8182-9ca81fd1e37d)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
Completed

![Image](https://github.com/user-attachments/assets/93246f3c-5ad6-4bbe-ba9f-8cdaf8a11112)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni
Closed by Gauri in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
**version 1.1.7**
![image](https://github.com/user-attachments/assets/ea552408-706f-4906-a3de-8b518413df2d)
