### ISSUE TITLE
Storybook >Charts>Pie Chart> Small & large mobile view alignment issue color and chart.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#499]
**Describe the bug**
Pie Chart> Small & large mobile view alignment issue color and chart.

**To Reproduce**
1. Go to 'Charts'
2. Click on 'Pie Chart'
5. Click on 'Pie Chart'

**Screenshots**
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/4ab2a1aa-f196-4d73-b6da-a8f0f32c2e4b)

![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/a2781ea3-0216-4ed8-812e-7bbbccad4da5)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed - 

![image](https://github.com/user-attachments/assets/d2f00c33-3522-482a-a5f8-2ccd5f11ff81)

![image](https://github.com/user-attachments/assets/bbe0a8a8-814b-4380-9af5-6ce8d6127959)

**Comment by shivani-bhalerao** [comment]
@trivenikulkarni
"Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7."

**Comment by rameshwarkamandar** [comment]
**version 1.1.7**
![image](https://github.com/user-attachments/assets/dfe2a610-b3c5-401c-80c4-f3fa75bfb23b)

![image](https://github.com/user-attachments/assets/7b3d4804-0730-4c55-aa7a-897cb37c927d)
