### ISSUE TITLE
Bug : Api Scopes Basics > Component Rendering Issue

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#5]
While opening Storybook - Follow below steps for reproducing the issue
1. Go to Api Scopes basics 
2. Component is not rendering 

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/b82274a7-ae71-4484-9bc2-6447e88df170)

**Comment by neeraj-bhakre** [comment]
Not reproducible in current version
