### ISSUE TITLE
Storybook >Components>Billing>Default>Small and large mobile view first card is not display.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#500]
**Describe the bug**
1. Billing>Default>Small and large mobile view first card is not display.
2. Subscription>Default>Small and large mobile view first card is not display.

**To Reproduce**
1. Go to 'Components'
3. Click on 'Billing'
5. Click on 'Default'

**Screenshots**
Billing-
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/a987f686-0972-4972-8a73-b603a2734ad1)

Subscription-
![image](https://github.com/Wai-Technologies/raaghu-react/assets/155446782/a4f6e6d3-fd7e-4465-a0f2-a7f92bf0696b)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed-
Billing-
![Image](https://github.com/user-attachments/assets/a86e92e4-1acc-471a-9e64-752ca7e2b997)

Subscription-
![Image](https://github.com/user-attachments/assets/ff8801c0-1e17-4f0e-98c9-0bb47199d660)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7

**Comment by rameshwarkamandar** [comment]
**version 1.1.7**
![image](https://github.com/user-attachments/assets/da108dbd-8902-4435-9de6-58fc2294e1d0)

![image](https://github.com/user-attachments/assets/a7ddb847-7554-4777-90e1-2ffd772fb293)
