### ISSUE TITLE
Design System > Element File Uploader : Unable to upload multiple files

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#504]
File Uploader:
o	Bug: In multiple upload scenarios, the file list array does not append correctly.

o	Steps to Reproduce:
1.	Upload one file and observe the uploaded file displayed on the screen.
2.	Upload two more files. Only the newly uploaded files are displayed instead of all three.

o	Expected Behavior: All three files should be displayed.

**Comment by rameshwarkamandar** [comment]
Completed - 
![image](https://github.com/user-attachments/assets/9d780fd9-6a58-443c-948b-47e391b20d4b)
