### ISSUE TITLE
Storybook >Components>Datatable> Action Button on Left Side> Action modal is opening but on mouse hover edit is hide

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#509]
**Describe the bug**
Datatable> Action Button on Left Side> Action modal is opening but on mouse hover edit is hide.

**To Reproduce**
1. Go to 'Components'
2. Click on 'Datatable'
3.  Click on 'Action Button on Left Side'

**Screenshots**
![image](https://github.com/user-attachments/assets/c5b61e17-21f9-47a7-aed0-bf2859b6b97a)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
Edit should not be hide


![Image](https://github.com/user-attachments/assets/39bd03f2-91c2-4531-b5cb-133b2a13c6b3)

**Comment by BhakareAbhishek** [comment]
I have check the above changes but its working fine from my side. I have check at react.raaghu.ai on both Microsoft edge and Chrome also. I have attached the image for reference.
![Image](https://github.com/user-attachments/assets/6d8053e5-4314-4206-8cfd-0a28d6719c8a)

**Comment by rameshwarkamandar** [comment]
Completed -

![Image](https://github.com/user-attachments/assets/03586a80-af07-4bc2-9936-55d3d56c16ee)
