### ISSUE TITLE
Storybook >Components>Developer Mode> Default>Add URL validation.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#510]
**Describe the bug**
1.Developer Mode> Default>Add URL validation.
2.Identity Client Basic> Default>apply URL validation & check all components.

**To Reproduce**
1. Go to 'Components'
2. Click on 'Developer Mode'
3. Click on 'Default'

**Screenshots**
![image](https://github.com/user-attachments/assets/e1f646a3-349d-4235-861c-f50f2702c924)

![image](https://github.com/user-attachments/assets/a7c54645-9494-44d5-be61-913946f85d3a)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
Completed


![Image](https://github.com/user-attachments/assets/3569f990-4765-435b-b7e3-01eaf61a06a0)



![Image](https://github.com/user-attachments/assets/93d57e46-18eb-410e-97c2-9c23620ec836)

**Comment by rameshwarkamandar** [comment]
**Version 1.1.7**
![image](https://github.com/user-attachments/assets/3c8057d2-236a-48f7-9664-53d9ee232f34)

![image](https://github.com/user-attachments/assets/f8235276-101d-4919-868b-10265b32e95b)
