### ISSUE TITLE
Storybook >Components>Cache>Default> Text spacing issues

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#516]
**Describe the bug**
1. Cache>Default> Text spacing issues.
2. Cache>Pagination> Text spacing issues.

**To Reproduce**
1. Go to 'Components'
2. Click on 'Cache'
3.  Click on 'Default'

**Screenshots**
![image](https://github.com/user-attachments/assets/f2973351-a32d-4cb4-8d65-7e4b442f5047)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
Completed


![Image](https://github.com/user-attachments/assets/122136f9-a868-4944-a0da-8ecc87a075a1)



![Image](https://github.com/user-attachments/assets/0cec9464-ccb7-4486-acc8-71d390f52500)

**Comment by rameshwarkamandar** [comment]
**Version 1.1.7**

![image](https://github.com/user-attachments/assets/8f08f814-211f-468b-a2c6-14913d720edc)

![image](https://github.com/user-attachments/assets/3babfdd8-ece1-406e-8010-cc197893e52c)
