### ISSUE TITLE
Storybook >Charts>Stacked Chart> Small and large mobile view, Tablet, reset viewport is not display proper.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#526]
**Describe the bug**
Charts>Stacked Chart> Small and large mobile view, Tablet, reset view port is not display proper.

**To Reproduce**
1. Go to 'Charts'
2. Click on 'Stacked Chart'
3. Click on 'Stacked Chart'

**Screenshots**
Small Mobile-
![image](https://github.com/user-attachments/assets/00ec4dea-b8f9-454f-a5a2-612a2b59e919)

Large Mobile -
![image](https://github.com/user-attachments/assets/5ee0e56f-c7d1-4de1-b822-fccb19258949)

Tablet-
![image](https://github.com/user-attachments/assets/4cd394da-0058-4e29-84c7-d25ff6bbf4a6)

Reset viewport -
![image](https://github.com/user-attachments/assets/99d051be-7510-45b0-a53f-20cafa78e659)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
For small and large mobile view, View Report is not displayed proper.


![Image](https://github.com/user-attachments/assets/95559077-5cc6-4ccd-b26e-819929cb33b0)



![Image](https://github.com/user-attachments/assets/4510da3b-c215-4376-88a5-0ade916ca9d4)

**Comment by rameshwarkamandar** [comment]
Completed -
![image](https://github.com/user-attachments/assets/9c549cb2-2178-43a7-be51-790fde3e31c6)

![image](https://github.com/user-attachments/assets/0a8a6511-74ba-4eb4-9fa9-ebd8920fc209)

![image](https://github.com/user-attachments/assets/5a8d910a-503e-4b12-8759-5562ab590a1e)
