### ISSUE TITLE
Design System > Implement Contributor Component in Storybook

### ISSUE THREAD

**Issue by kaushikgokhale** [Wai-Technologies/raaghu-react#529]
## Description:
 
Create a Contributor Layout which consists of following Actions as part of flow,
1. We should be able to change Change panel colors
2. We should be able to change Change label texts
3. We should be able to change Change styles by overwriting SVG attributes

## URL's to refer:
https://reactscript.com/github-like-heatmap-calendar-react/
http://haripo.github.io/react-github-contribution-calendar/

**Comment by hemalatagaikwad** [comment]
Completed task need to review by @Ketan-Khalate

**Comment by rameshwarkamandar** [comment]
Completed -

![image](https://github.com/user-attachments/assets/b8345f2b-630e-436b-9ef2-521fb5963505)

![image](https://github.com/user-attachments/assets/a18c3150-59dd-4686-b6b1-f791f1ee3ce1)
