### ISSUE TITLE
Storybook >Elements>Review Category>Default> Selecting dark theme star color is not change

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#531]
**Describe the bug**
Review Category>Default> Selecting dark theme star color is not change.
Check Center Align, Left Align

**To Reproduce**
1. Go to 'Elements'
2. Click on 'Review Category'
3. Click on 'Default'

**Screenshots**
![image](https://github.com/user-attachments/assets/d8c16724-7ed9-4ce1-97d4-5798559e882f).

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by rameshwarkamandar** [comment]
Completed - 

Default-

![Image](https://github.com/user-attachments/assets/be597aa6-34de-418e-8508-0cdab74c0c24)

Center Aligned -

![Image](https://github.com/user-attachments/assets/e7b73ced-7034-4387-b6c7-6f87df982016)

Left Aligned-

![Image](https://github.com/user-attachments/assets/e4dcd178-31c6-4bfe-afa7-ffa25ace5b5a)

**Comment by pravinwaghmare23** [comment]
@trivenikulkarni
Closed by Rameshwar in version 1.1.6, which is available in version 1.1.7
