### ISSUE TITLE
Review design system to identify name with word "New" and do required changes

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#537]
Review design system to identify name with word "New" and do required changes

![Image](https://github.com/user-attachments/assets/1da3e5fb-91e1-46c3-a2e2-35406257f0c5)

**Comment by gauri1307** [comment]
Completed



![Image](https://github.com/user-attachments/assets/43682b94-3404-46e7-9607-4572df9e0e1d)

**Comment by rameshwarkamandar** [comment]
Issue still exists on Staging

![image](https://github.com/user-attachments/assets/f710b6a2-37fc-49e2-861e-81de67db2586)

**Comment by rameshwarkamandar** [comment]
Completed-

![image](https://github.com/user-attachments/assets/ccd42873-20bd-4ffa-85ef-7f466d842345)
