### ISSUE TITLE
Build verification : 1.1.6 deployed on 17th July

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#541]
Build verification : 1.1.6 deployed on 17th July

![Image](https://github.com/user-attachments/assets/5d09b9a5-6fc3-4fd0-ae89-f48879f4faf8)

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Task ID | Status | Worked On
-- | -- | -- | -- | --
1 | Components   > Api resource basic > Ui label name and action data name are different   · Issue #403 · Wai-Technologies/raaghu-react (github.com) | 403 | Already Closed | Akshay
2 | Storybook   > Components >Alert Popup > Default > When click on Alert Popup   button and go to next component is not working. · Issue #449 ·   Wai-Technologies/raaghu-react (github.com) | 449 | Already Closed | Akshay
3 | https://github.com/Wai-Technologies/raaghu-react/issues/452 | 452 | Already Closed | Akshay
4 | Bug :   Component > Profile edit > Image is missing · Issue #307 ·   Wai-Technologies/raaghu-react (github.com) | 307 | Already Closed | Akshay
5 | https://github.com/Wai-Technologies/raaghu-react/issues/400 | 400 | Already Closed | Akshay
6 | https://github.com/Wai-Technologies/raaghu-react/issues/436 | 436 | Already Closed | Akshay
7 | Storybook   > Components >Features New > Default >Restore to Default and Save   buttons are not working. · Issue #437 · Wai-Technologies/raaghu-react   (github.com) | 437 | Already Closed | Akshay
8 | Storybook   > Components >Organization Tree> Default > Three dots button   isn't clickable. · Issue #438 · Wai-Technologies/raaghu-react (github.com) | 438 | Already Closed | Akshay
9 | Storybook   > Components >Visual Setting > Default >Alignment issue   Subheader, Menu, Footer, click on dropdown chevron is not upward and downward   · Issue #448 · Wai-Technologies/raaghu-react (github.com) | 448 | Reopen | Akshay
10 | https://github.com/Wai-Technologies/raaghu-react/issues/460 | 460 | Already Closed | Akshay
11 | https://github.com/Wai-Technologies/raaghu-react/issues/463 | 463 | Already Closed | Akshay
12 | Storybook   > Elements>Navbar > Default >Selecting dark theme navbar content   is not display · Issue #464 · Wai-Technologies/raaghu-react (github.com) | 464 | Already Closed | Akshay
13 | https://github.com/Wai-Technologies/raaghu-react/issues/465 | 465 | Already Closed | Akshay
14 | DS >   Implement Changes to Urls through application for Updated Urls · Issue #469 ·   Wai-Technologies/raaghu-react (github.com) | 469 | Already Closed | Pravin
15 | https://github.com/Wai-Technologies/raaghu-react/issues/466 | 466 | Already Closed | Akshay
16 | https://github.com/Wai-Technologies/raaghu-react/issues/275 | 275 | Already Closed | Pravin
17 | Add newly   designed and existing updated Layout from Abel Systems · Issue #475 ·   Wai-Technologies/raaghu-react (github.com) | 475 | Closed | Shivani
18 | Storybook   > Components >Download Collection> Default > After click on   download icon no data display in action · Issue #429 ·   Wai-Technologies/raaghu-react (github.com) | 429 | Reopen | Akshay
19 | Implement   Top Navigation With Search · Issue #478 · Wai-Technologies/raaghu-react   (github.com) | 478 | Already Closed | Shivani
20 | Elements   >Notification> Selecting dark theme button text is not display. · Issue   #470 · Wai-Technologies/raaghu-react (github.com) | 470 | Closed | Pravin
21 | Storybook   > Elements >Card Detail >Selecting small mobile view radio button is   stick on card text. · Issue #481 · Wai-Technologies/raaghu-react (github.com) | 481 | Already Closed | Pravin
22 | https://github.com/Wai-Technologies/raaghu-react/issues/467 | 467 | Already Closed | Akshay
23 | Storybook   > Elements >Button> Default >Selecting dark theme colorVariant   light button text is not display. · Issue #482 ·   Wai-Technologies/raaghu-react (github.com) | 482 | Already Closed | Akshay
24 | https://github.com/Wai-Technologies/raaghu-react/issues/485 | 485 | Already Closed | Akshay
25 | https://github.com/Wai-Technologies/raaghu-react/issues/499 | 499 | Closed | Shivani
26 | Storybook   > Elements >Input >Email>Unable to fill data. · Issue #488 ·   Wai-Technologies/raaghu-react (github.com) | 488 | Closed | Akshay
27 | Storybook   >Components>Email>Default>Hide form content · Issue #495 ·   Wai-Technologies/raaghu-react (github.com) | 495 | Closed | Akshay
28 | Storybook   > Elements >Stat>Default>Dark theme Icon color is not change ·   Issue #496 · Wai-Technologies/raaghu-react (github.com) | 496 | Closed | Pravin
29 | Storybook   >Elements>Feed> Select dark theme star color is not change. · Issue   #511 · Wai-Technologies/raaghu-react (github.com) | 511 | Reopen | Pravin
30 | Change   path from Angular reference to current repo of storybook · Raaghu Design   System Storybook - React (github.com) | 498 | Reopen| Shivani



</body>

</html>
Reopen- 4
Closed - 6
Already Closed- 20
