### ISSUE TITLE
Write test scenarios and do testing of newly added components

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#544]
Write test scenarios and do testing of newly added components

1	Top Navigation With Search
2	Get Assistance
3	Hierarcy
4	Order Confirmation
5	Premium Support
6	Purchase Developer Seats
7	Copy Text
8	Invoice Detail Receipt
9	Collapsible Container

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Module \ Submodule | Feature | Scenario | Remark | Status
-- | -- | -- | -- | -- | --
1 |   | Collapsible Container/Docs | Verify outline  preview |   |  
  |   |   | Verify Theme Clear theme, Light   , Dark |   |  
  |   |   | Zoom in zoom out Reset zoom,   Show code |   |  
  |   |   | Name, Descriptio, Default,   Control reset control |   |  
  |   |   |   |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
  |   |   | Alignment issue | Alignment issue | Fail
2 |   | Get Assistance/ Docs | Verify   outline  preview |   |  
  |   |   | Verify Theme   Clear theme, Light , Dark |   |  
  |   |   | Zoom in zoom   out Reset zoom, Show code |   |  
  |   |   | Name,   Descriptio, Default, Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - After submiting Data is   display in action |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
3 |   | Hierarcy/ Docs | Verify outline  preview |   |  
  |   |   | Verify Theme Clear theme, Light   , Dark |   |  
  |   |   | Zoom in zoom out Reset zoom,   Show code |   |  
  |   |   | Name, Descriptio, Default,   Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - After submiting Data is   display in action |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
4 |   | Order Confirmation/ Docs | Verify   outline  preview |   |  
  |   |   | Verify Theme   Clear theme, Light , Dark |   |  
  |   |   | Zoom in zoom   out Reset zoom, Show code |   |  
  |   |   | Name,   Descriptio, Default, Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - After submiting Data is   display in action |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
5 |   | Premium Support/ Docs | Verify outline  preview |   |  
  |   |   | Verify Theme Clear theme, Light   , Dark |   |  
  |   |   | Zoom in zoom out Reset zoom,   Show code |   |  
  |   |   | Name, Descriptio, Default,   Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - After submiting Data is   display in action |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
  |   |   | Small & large mobile view   Card spacing and alignment issue | Small & large mobile view Card spacing and alignment issue | Fail
6 |   | Purchase Developer Seats/ Docs | Verify   outline  preview |   |  
  |   |   | Verify Theme   Clear theme, Light , Dark |   |  
  |   |   | Zoom in zoom   out Reset zoom, Show code |   |  
  |   |   | Name,   Description, Default, Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - After submiting Data is   display in action |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
7 |   | Copy Text / Docs | Verify outline  preview |   |  
  |   |   | Verify Theme Clear theme, Light   , Dark |   |  
  |   |   | Zoom in zoom out Reset zoom,   Show code |   |  
  |   |   | Name, Description, Default,   Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
8 |   | Invoice Detail Receipt/ Docs | Verify   outline  preview |   |  
  |   |   | Verify Theme   Clear theme, Light , Dark |   |  
  |   |   | Zoom in zoom   out Reset zoom, Show code |   |  
  |   |   | Name,   Description, Default, Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
  |   |   | Small & large mobile view   Invoice Detail Receipt is not proper alignment | Small & large mobile view   Invoice Detail Receipt is not proper alignment | Fail
9 |   | Top Navigation With Search/ Docs | Verify outline  preview |   |  
  |   |   | Verify Theme Clear theme, Light   , Dark |   |  
  |   |   | Zoom in zoom out Reset zoom,   Show code |   |  
  |   |   | Name, Description, Default,   Control reset control |   |  
  |   | Default | Remount component , Zoom in zoom   out Reset zoom |   |  
  |   |   | Size of  preview, Enable measure, Outline preview,   Theme Clear theme, Light , Dark |   |  
  |   |   | Controls- Name, Control , Reset   control Are working |   |  
  |   |   | Action - |   |  
  |   |   | Interaction - |   |  
  |   |   | Change addon, Hide |   |  
  |   |   | Small & large mobile view   language popup is hide | Small & large mobile view   language popup is hide | Fail
  |   |   |   |   |  
  |   |   |   |   |  



</body>

</html>
