### ISSUE TITLE
Storybook > Components>Premium Support>Small & large mobile view Card spacing and alignment issue

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#551]
**Describe the bug**
Components>Premium Support>Small & large mobile view Card spacing and alignment issue

**To Reproduce**
1.Go to 'Storybook'
2.Click on 'Components'
3.Click on 'Premium Support'
4.Click on 'Default'

**Screenshots**
![image](https://github.com/user-attachments/assets/b0c1eb06-502b-4db9-ad51-0bc82607327e)

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Smartphone (please complete the following information):NA**

**Additional context**

**Comment by gauri1307** [comment]
Completed


![Image](https://github.com/user-attachments/assets/6e996efc-81bd-4592-9558-69f627a13fcd)



![Image](https://github.com/user-attachments/assets/ca070d5b-5ed5-4d09-882a-7c0bc7f1c6b6)

**Comment by rameshwarkamandar** [comment]
**Version 1.1.7**
![image](https://github.com/user-attachments/assets/40e5d6d8-4177-4141-ad91-2d9314e34114)
