### ISSUE TITLE
Design System > Component >Edition New Basic	: Validation missing for Edition Name. No error message if its kept empty

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#574]
**Describe the bug**
Validation missing for Edition Name. No error message if its kept empty
 
**Steps to reproduce bug**
1.Go to https://react.raaghu.ai/
2. Navigate to 'Components>Edit New Basic'
3.Submit without entering Edition Name
 
**Actual result-**
Validation missing for Edition Name. No error message if its kept empty
 
**Screenshots**
 
**Expected result-**
Proper error handling should be done
 
**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
![Image](https://github.com/user-attachments/assets/16aa6b3f-29ad-4727-9ef1-9f3e7bf58a63)

**Comment by rameshwarkamandar** [comment]
Completed - 
![image](https://github.com/user-attachments/assets/8bc8a54c-0a40-4a5c-99bb-a698952855af)
