### ISSUE TITLE
Design System > Implement different types Buttons

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#591]
Add new element for different types of Buttons with reference of below link
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=605-9960

**Comment by rameshwarkamandar** [comment]
1. isRoundedButton True - LoadingSpinner is not show.
2. isRoundedButton False- LoadingSpinner is show.
3. showLoadingSpinner True and  isRoundedButton True that time click on button display square.


![image](https://github.com/user-attachments/assets/9c17013c-eb0c-449f-bdae-f9ff48892df2)

**Comment by rameshwarkamandar** [comment]
Loading Spinner is display proper.
![image](https://github.com/user-attachments/assets/b69a6c67-d22d-4b73-90e7-e34d86c4c8d4)
