### ISSUE TITLE
Build verification : Deployment done on 25th July 2024 [Part1]

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#595]

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Task ID | Status | Worked On | Test By
-- | -- | -- | -- | -- | --
1 | Storybook   >Components>Delivery Method> Default>Choose a dark theme, add a   grey card color, and make sure the description is hidden. · Raaghu Design   System Storybook - React (github.com) | 507 | Closed | Akshay | Rameshwar
2 | https://github.com/orgs/Wai-Technologies/projects/16/views/1?filterQuery=status%3AResolved&groupedBy%5BcolumnId%5D=Assignees&pane=issue&itemId=70458328 | 489 | Closed | Pravin | Rameshwar
3 | https://github.com/orgs/Wai-Technologies/projects/16/views/1?filterQuery=+status%3AReopen&groupedBy%5BcolumnId%5D=Assignees&pane=issue&itemId=70555684 | 494 | Reopen | Pravin | Rameshwar
4 | Storybook   > Elements >Bank Card Detail >Selecting small mobile view radio   button is stick on card text. · Raaghu Design System Storybook - React   (github.com) | 543 | Closed | Ashok | Rameshwar
5 | Storybook   > Components>User Basics >Placeholder is not proper and Add phone no   validation · Raaghu Design System Storybook - React (github.com) | 547 | Closed | Ashok | Rameshwar
6 | Storybook   > Components>Tenant Settings >Placeholder and warning Issue. ·   Raaghu Design System Storybook - React (github.com) | 550 | Closed | Ashok | Rameshwar
7 | Storybook   >Components>Profile Edit>Error message is not proper · Raaghu Design   System Storybook - React (github.com) | 554 | Closed | Ashok | Rameshwar
8 | Storybook   >Components>Shipping Address > Invalid placeholder · Raaghu Design   System Storybook - React (github.com) | 557 | Closed | Ashok | Rameshwar
9 | Storybook   >Components>Theme New > Invalid placeholder · Raaghu Design System   Storybook - React (github.com) | 563 | Reopen | Ashok | Rameshwar
10 | Storybook   > Component > User Delegations > Default > After submitting End   date start date is not display in action · Raaghu Design System Storybook -   React (github.com) | 417 | Closed | Sachin | Rameshwar
11 | Storybook   >Charts>Scatter Chart>Docs> Stories Scatter Chart through error.   · Raaghu Design System Storybook - React (github.com) | 522 | Closed | Pravin | Rameshwar
12 | Storybook   >Elements>Review Category>Default> Selecting dark theme star   color is not change · Raaghu Design System Storybook - React (github.com) | 531 | Closed | Pravin | Rameshwar
13 | Storybook   >Components>Billing>Default>Small and large mobile view first   card is not display. · Raaghu Design System Storybook - React (github.com) | 500 | Closed | Pravin | Rameshwar
14 | https://github.com/orgs/Wai-Technologies/projects/16/views/1?filterQuery=status%3AResolved+assignee%3A&groupedBy%5BcolumnId%5D=Assignees&pane=issue&itemId=68125728 | 429 | Closed | Akshay | Rameshwar
15 | Storybook   >Loader> Line Wobble >Select dark theme Line Wobble loader is not   display · Raaghu Design System Storybook - React (github.com) | 491 | Closed | Akshay | Rameshwar
16 | Storybook   > Elements >Popover >Selecting small, large mobile view popover   Position left is not proper. · Raaghu Design System Storybook - React   (github.com) | 492 | Closed | Akshay | Rameshwar
17 | Storybook   >Elements> Website Matrix>Default> Remove the hand cursor learn   more arrow from all stories. · Raaghu Design System Storybook - React   (github.com) | 521 | Closed | Akshay | Rameshwar
18 | Storybook   >Components>New Menu>Default>Add URL Validation and Page select   no option is there. · Raaghu Design System Storybook - React (github.com) | 525 | Closed | Akshay | Rameshwar



</body>

</html>
Closed = 16
Reopened = 2
