### ISSUE TITLE
Build verification : Deployment done on 25th July 2024 [Part2]

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#596]

**Comment by gauri1307** [comment]
Completed
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/GAURIJ~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/GAURIJ~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr No. | Bug Title | Task ID | Status | Worked On | Test By
-- | -- | -- | -- | -- | --
1 | Storybook   > Elements >Toast>Toast without header>Cross icon alignment issue   · Issue      #497 · Wai-Technologies/raaghu-react   (github.com) | 497 | Closed | Pravin | Gauri
2 | https://github.com/Wai-Technologies/raaghu-react/issues/526#issuecomment-2252152367 | 526 | Reopen | Abhishek | Gauri
3 | Storybook   > Components>Premium Support>Small & large mobile view Card   spacing and     alignment issue · Issue #551 · Wai-Technologies/raaghu-react (github.com) | 551 | Closed | Akshay | Gauri
4 | Storybook   >Components>Cache>Default> Text spacing issues · Issue #516 ·   Wai-     Technologies/raaghu-react (github.com) | 516 | Closed | Akshay | Gauri
5 | Storybook   >Components>Datatable> Action Button on Left Side> Action modal   is opening but on mouse hover edit is hide · Issue #509 ·   Wai-Technologies/raaghu-react (github.com) | 509 | Reopen | Abhishek | Gauri
6 | Storybook   >Components>Developer Mode> Default>Add URL validation. · Issue   #510 · Wai-Technologies/raaghu-react (github.com) | 510 | Closed | Akshay | Gauri



</body>

</html>
