### ISSUE TITLE
Bug : Application Scopes > Component Rendering Issue

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#6]
Go to Storybook - Follow below steps for reproducing the issue
1. Go to Application Scopes
2. Component is not rendering 

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/b1b876a0-874d-4ad7-9102-05684e462bef)

**Comment by suraj-khupse** [comment]
Issue Resolved in current deployment.

**Comment by rameshwarkamandar** [comment]
As this issue already in closed state. closing this now
