### ISSUE TITLE
Design System > Implement different Divide bar

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#601]
1.Review existing dividebar in storybook
2.For non existing , Add new element for different additional types with reference of below link
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=605-9960

![Image](https://github.com/user-attachments/assets/1815e7c9-1523-45a2-9f8d-163467f800a0)

**Comment by rameshwarkamandar** [comment]
Completed -

![image](https://github.com/user-attachments/assets/31adce70-5f16-4ef9-895f-0195525fff8e)
