### ISSUE TITLE
Application Shell > Implement Application Shell for Portal to Storybook in App Shell Section

### ISSUE THREAD

**Issue by kaushikgokhale** [Wai-Technologies/raaghu-react#610]
Add App Shell from Raaghu Portal to Storybook > App Shell Section

**Comment by kaushikgokhale** [comment]
@trivenikulkarni please assign this to developer

**Comment by rameshwarkamandar** [comment]
Completed -

![Image](https://github.com/user-attachments/assets/6acfca88-cba2-4f74-956a-80daf0da2e94)
