### ISSUE TITLE
Storybook > End to end testing on staging environment [Build1 Version : 1.17, Sprint4] 

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#622]
Storybook > End to end testing and bug retesting of  below list 

![Image](https://github.com/user-attachments/assets/7d74a5c2-21a5-4bf4-a83d-1a6956602988)

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bud/Task ID | Status | Worked On
-- | -- | -- | -- | --
1 | Bug :   Component > Hide Unused components · Issue #275 ·   Wai-Technologies/raaghu-react (github.com) | 275 | Reopen | Pravin
2 | Add newly   designed and existing updated Layout from Abel Systems · Issue #475 ·   Wai-Technologies/raaghu-react (github.com) | 475 | Already Closed | Shivani
3 | Add newly   designed and existing updated components from A. S · Issue #472 ·   Wai-Technologies/raaghu-react (github.com) | 472 | Reopen | Akshay
4 | Storybook   > Components >Download Collection> Default > After click on   download icon no data display in action · Issue #429 ·   Wai-Technologies/raaghu-react (github.com) | 429 | Already Closed | Akshay
5 | Storybook   > Components >Visual Setting > Default >Alignment issue   Subheader, Menu, Footer, click on dropdown chevron is not upward and downward   · Issue #448 · Wai-Technologies/raaghu-react (github.com) | 448 | Reopen | Akshay
6 | Implement   Top Navigation With Search · Issue #478 · Wai-Technologies/raaghu-react   (github.com) | 478 | Already Closed | Shivani
7 | Elements   >Notification> Selecting dark theme button text is not display. · Issue   #470 · Wai-Technologies/raaghu-react (github.com) | 275 | Already Closed | Pravin
8 | Storybook   > Elements >Card Detail >Selecting small mobile view radio button is   stick on card text. · Issue #481 · Wai-Technologies/raaghu-react (github.com) | 481 | Already Closed | Pravin
9 | Elements   >Counter > Selecting light theme & color Variant light outline is   not display. · Issue #467 · Wai-Technologies/raaghu-react (github.com) | 467 | Already Closed | Akshay
10 | Storybook   > Elements >Button> Default >Selecting dark theme colorVariant   light button text is not display. · Issue #482 ·   Wai-Technologies/raaghu-react (github.com) | 482 | Already Closed | Akshay
11 | Storybook   > Elements >Card> Avatar >Unable to see image. · Issue #485 ·   Wai-Technologies/raaghu-react (github.com) | 485 | Already Closed | Akshay
12 | Change   path from Angular reference to current repo of storybook · Issue #498 ·   Wai-Technologies/raaghu-react (github.com) | 498 | Already Closed | Shivani
13 |   |   |   |  
14 |   |   |   |  
15 |   |   |   |  



</body>

</html>
Reopen = 3
Already Closed = 9

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bud/Task ID | Status | Worked On
-- | -- | -- | -- | --
1 | Storybook   >Charts>Pie Chart> Small & large mobile view alignment issue   color and chart. · Issue #499 · Wai-Technologies/raaghu-react (github.com) | 499 | Already Closed | Shivani
2 | Storybook   > Elements >Input >Email>Unable to fill data. · Issue #488 ·   Wai-Technologies/raaghu-react (github.com) | 488 | Already Closed | Akshay
3 | Storybook   >Components>Email>Default>Hide form content · Issue #495 ·   Wai-Technologies/raaghu-react (github.com) | 495 | Already Closed | Akshay
4 | Storybook   > Elements >Stat>Default>Dark theme Icon color is not change ·   Issue #496 · Wai-Technologies/raaghu-react (github.com) | 496 | Already Closed | Pravin
5 | Storybook   >Elements>Feed> Select dark theme star color is not change. · Issue   #511 · Wai-Technologies/raaghu-react (github.com) | 511 | Closed | Pravin
6 | Storybook   >Loader> Line Wobble >Select dark theme Line Wobble loader is not   display · Issue #491 · Wai-Technologies/raaghu-react (github.com) | 491 | Already Closed | Akshay
7 | Storybook   >Components>Delivery Method> Default>Choose a dark theme, add a   grey card color, and make sure the description is hidden. · Issue #507 ·   Wai-Technologies/raaghu-react (github.com) | 507 | Already Closed | Akshay
8 | Storybook   >Components>Developer Mode> Default>Add URL validation. · Issue   #510 · Wai-Technologies/raaghu-react (github.com) | 510 | Already Closed | Akshay
9 | Storybook   > Elements >Product Image >Column Layout> Alignment Issue. ·   Issue #489 · Wai-Technologies/raaghu-react (github.com) | 489 | Reopen | Pravin
10 | Storybook   > Component > User Delegations > Default > After submitting End   date start date is not display in action · Issue #417 ·   Wai-Technologies/raaghu-react (github.com) | 417 | Already Closed | Sachin
11 | Storybook   > Elements >Scrollspy>Default>Small and large mobile view card   content and button overlap · Issue #494 · Wai-Technologies/raaghu-react   (github.com) | 494 | Reopen | Pravin
12 | Storybook   > Elements >Toast>Toast without header>Cross icon alignment issue   · Issue #497 · Wai-Technologies/raaghu-react (github.com) | 497 | Already Closed | Pravin
13 | Storybook   >Elements>Review Category>Default> Selecting dark theme star   color is not change · Issue #531 · Wai-Technologies/raaghu-react (github.com) | 531 | Already Closed | Pravin
14 | Storybook   >Components>Cache>Default> Text spacing issues · Issue #516 ·   Wai-Technologies/raaghu-react (github.com) | 516 | Already Closed | Akshay
15 | Storybook   >Elements> Website Matrix>Default> Remove the hand cursor learn   more arrow from all stories. · Issue #521 · Wai-Technologies/raaghu-react   (github.com) | 521 | Already Closed | Akshay
16 | https://github.com/Wai-Technologies/raaghu-react/issues/525 | 525 | Already Closed | Akshay
17 | https://github.com/Wai-Technologies/raaghu-react/issues/522 | 522 | Already Closed | Pravin
18 | https://github.com/Wai-Technologies/raaghu-react/issues/500 | 500 | Already Closed | Akshay
19 | https://github.com/Wai-Technologies/raaghu-react/issues/508 | 508 | Reopen | Pravin
20 | Storybook   > Elements >Bank Card Detail >Selecting small mobile view radio   button is stick on card text. · Issue #543 · Wai-Technologies/raaghu-react   (github.com) | 543 | Already Closed | Ashok
21 | Design   System > Element File Uploader : Unable to upload multiple files · Issue   #504 · Wai-Technologies/raaghu-react (github.com) | 504 | Closed | Supriya
22 | Review   design system to identify name with word "New" and do required   changes · Issue #537 · Wai-Technologies/raaghu-react (github.com) | 537 | Reopen | Akshay
23 | Storybook   > Components>User Basics >Placeholder is not proper and Add phone no   validation · Issue #547 · Wai-Technologies/raaghu-react (github.com) | 547 | Already Closed | Ashok
24 | https://github.com/Wai-Technologies/raaghu-react/issues/550 | 550 | Already Closed | Ashok
25 | https://github.com/Wai-Technologies/raaghu-react/issues/554 | 554 | Already Closed | Ashok
26 | Storybook   >Charts>Stacked Chart> Small and large mobile view, Tablet, reset   viewport is not display proper. · Issue #526 · Wai-Technologies/raaghu-react   (github.com) | 526 | Closed | Abhishek
27 | https://github.com/Wai-Technologies/raaghu-react/issues/557 | 557 | Reopen | Ashok
28 | Storybook   > Components >Download Collection> Default > After click on   download icon no data display in action · Issue #429 ·   Wai-Technologies/raaghu-react (github.com) | 429 | Already Closed | Akshay
29 | https://github.com/Wai-Technologies/raaghu-react/issues/492 | 492 | Already Closed | Akshay
30 | https://github.com/Wai-Technologies/raaghu-react/issues/551 | 551 | Already Closed | Akshay
31 | https://github.com/Wai-Technologies/raaghu-react/issues/563 | 563 | Closed | Ashok



</body>

</html>
Closed = 4
Already Closed = 22
Reopen = 5
