### ISSUE TITLE
Design System 7.6.20 > Issues of components

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#624]
**Describe the bug**
Design System 7.6.20 > Issues of components

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Sr.No | Components | Issues
-- | -- | --
1 | Address Input | in control   address  name mistake.
2 | Blog List | in small & large   mobile view pagination alignment is not proper.
3 | Cache | in small & large   mobile view pagination alignment is not proper.
4 | Claims | in a small mobile   view button alignment not show properly.
5 |   | when select claim   type dropdown some value hide behind the table.
6 |   | when add cliam types   and claim value after that claim types dropdown not clear.
7 | Collapsible Container | in a dark theme icon   not show.
8 | Contact Us | in a dark theme   Message placeholder text color not show properly.
9 | Cookie Section | in a small ,large,   tablet view  cookie section alignment   not show properly.
10 |   | in a dark theme   decline button text not show properly.
11 | Developer Mode | in a dark theme   Application Grant Type placeholder text not show properly.
12 | Feature | in a dark theme =>   identity => two factor behaviour dropdown text not show in color.
13 | Forgot Password | in a dark theme small   , large view select language not show properly.
14 | Invoice Detail   Receipt | in small and large   mobile view data not show properly.
15 | Invoice | in a dark theme   placeholder text color not show properly.
16 | Login | in a small , large ,   tablet  select language dropdown not   show properly.
17 | My Settings | in a confirm new   password validation error message not show properly.
18 | Product Image | in a dark theme some   text color not show properly.
19 | Product List | in a dark theme text   color not show properly.
20 | Profile Edit | in a dark theme label   color not show properly.
21 | Shipping Address | in a small mobile   view address text not show properly.
22 | Shopping Cart | in a dark theme   selected quantity dropdown value text color not show properly.
23 | Summary Details | in a small , large   mobile view all text alignment not show properly.
24 | Tenant Dashboard | in a dark theme some   card not show in proper color.
25 | Tenant   Information | in a dark theme   selected edition text color not show properly.
26 | Tenant Management | small and large   mobile view edtion dropdown not show properly.
27 | Top Navigation With   Search | small and large   mobile view language dropdown not show properly.
28 | User Delegations | in small mobile view   save button alignment not show properly.
29 | User Table | in small mobile view   click on actions three dot , open a poup that time option not show properly.
30 | Visual Setting | in dark theme click   on any  subheader , menu and fotter so   in that text color not show properly.
31 | Webhook Subscription | in small mobile view   Add button overlap on a textbox.
32 | Change Password | new password confirm   error messsage validation not show properly.
33 | Login Attempts | in small mobile view   select date range that select box not show properly.

</body>

</html>

**Comment by ashoksinarewai** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ASHOKS~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ASHOKS~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#467886" vlink="#96607D">

I have completed this following components.

Sr.No | Components | Issues
-- | -- | -
1 | Address Input | in control address  name mistake.
2 | Collapsible Container | in a dark theme icon not show.
3 | Cookie Section | in a small ,large, tablet view    cookie section alignment not show properly.
4 | Forgot Password | in a dark theme small , large view select language not show   properly.
5 | Invoice Detail Receipt | in small and large mobile view data not show properly.
6 | Login | in a small , large , tablet    select language dropdown not show properly.
7 | My Settings | in a confirm new password validation error message not show   properly.
8 | Profile Edit | in a dark theme label color not show properly.
9 | Shipping Address | in a small mobile view address text not show properly.
10 | Tenant Dashboard | in a dark theme some card not show in proper color.
11 | Top Navigation With Search | small and large mobile view language dropdown not show   properly.
12 | User Delegations | in small mobile view save button alignment not show properly.
13 | Visual Setting | in dark theme click on any    subheader , menu and fotter so in that text color not show properly.
14 | Webhook Subscription | in small mobile view Add button overlap on a textbox.
15 | Change Password | new password confirm error messsage validation not show   properly.
16 | Change User  Password | new password confirm error messsage validation not show   properly.
17 | Login Attempts | in small mobile view select date range that select box not   show properly.
18 | Claims | when add cliam types and claim value after that claim types dropdown not clear.



</body>

</html>

**Comment by rameshwarkamandar** [comment]
Completed-
[Design System 7.6.20  Issues of components..docx](https://github.com/user-attachments/files/17043407/Design.System.7.6.20.Issues.of.components.docx)
