### ISSUE TITLE
Design System 7.6.20 > Issues of Elements, chart

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#625]
Design System 7.6.20 > Issues of Elements, chart

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Sr.No | Elements/Components | Issue
-- | -- | --
  | Elements |  
1 | Button Group | Open Checkbox button   group in small mobile view its not show properly.
2 | Collapse | Open Collapse in   small and large mobile view its not show properly.
3 | Modal | In a dark theme   vertically centered modal close button text not show properly.
4 | Notification | in a small mobile   view "SET AS READ"  button   text not show properly.
5 | Pagination | in a dark theme drop   down number not show properly.
  |   | in a advanced small   mobile view pagination dropdown alignment    not show properly.
6 | Popover | in a dark theme   button "POPOVER" color not show properly.
7 | Select List | in a dark theme   dropdown text color not show properly.
  |   | click on multiple   option => in a dropdown select list option not selected.
8 | Textarea | in a dark theme   placeholder text color not show properly.
9 | Toast | Toast without header   close button alignment not show properly.
  |   |  
  | Charts |  
10 | Doughnut Chart | in this chart Blue   color not show proper color.
  |   |  
11 | Application  Shells | In a small mobile   view => click on user icon =>personal data text hide behind the button.

</body>

</html>

**Comment by rameshwarkamandar** [comment]
1. Button Group -
![image](https://github.com/user-attachments/assets/dde79635-e9e6-4344-9171-05b9dd3d815f)

2. Collapse -
![image](https://github.com/user-attachments/assets/77d50134-a3d2-403b-8be3-67ac0495dd01)

![image](https://github.com/user-attachments/assets/7896e4a6-7a0d-453a-b2b9-c14b0780c726)

3. Modal -
![image](https://github.com/user-attachments/assets/2b2ee1ba-ecb2-4b3b-bf69-2c4928aebe5c)

4. Notification -
![image](https://github.com/user-attachments/assets/27756633-96c3-4525-80af-4b46ef3b2e0f)

5. Pagination -
![image](https://github.com/user-attachments/assets/f2557dc4-51c7-4194-8710-1db8edffabbc)

![image](https://github.com/user-attachments/assets/febfea3a-48e2-4a7a-9317-8d0b4aa39665)

6. Popover -
![image](https://github.com/user-attachments/assets/22c5d924-d6b3-4d25-867c-3001b833552b)

7. Select List -
![image](https://github.com/user-attachments/assets/9d6e06c0-26de-4fb8-823d-4306fd20a30d)

![image](https://github.com/user-attachments/assets/dfec3e1e-946e-41b7-9616-40ad5c451466)

8. Text area -
![image](https://github.com/user-attachments/assets/270748c5-b512-4e6c-b954-b5661c5bc3ac)

9. Toast -
![image](https://github.com/user-attachments/assets/85793663-e2d9-40bb-acd0-17574ec32a63)

10. Doughnut Chart -
![image](https://github.com/user-attachments/assets/7fa8d7dd-1c0e-4252-9bfe-4f897cb6fb99)

11. Application Shells -
![image](https://github.com/user-attachments/assets/7e091674-aa5a-4b71-a25f-e4f052fe6734)
