### ISSUE TITLE
Design System > Label is CICD instead of Ci/Cd

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#628]
Design System > Label is Ci/Cd instead of CICD

![Image](https://github.com/user-attachments/assets/e4e3e9bd-2b4c-43c8-8b9e-31143d47428e)

**Comment by rameshwarkamandar** [comment]
Complected -
![image](https://github.com/user-attachments/assets/8b040829-aa3b-4e8b-b241-923c06e69ad7)
