### ISSUE TITLE
Design System > Elements > Alert > App Details : Incorrect Word

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#629]
Design System > Elements > Alert > App Details : Incorrect Word

![Image](https://github.com/user-attachments/assets/01b44020-d119-403b-b3d0-96b883b89d0e)

**Comment by rameshwarkamandar** [comment]
Completed -
![image](https://github.com/user-attachments/assets/64dc6aef-5016-4471-95d2-1410d409a181)
