### ISSUE TITLE
Design System : Elements > Banner : Space is missing between word News and !

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#630]
Design System : Elements > Banner :  Space is missing between word News and !

![Image](https://github.com/user-attachments/assets/eb9610cf-c39d-420a-ac99-7176da0658c2)

**Comment by rameshwarkamandar** [comment]
Completed -
![image](https://github.com/user-attachments/assets/06cacfa3-171b-42ec-8a60-025c831fb683)
