### ISSUE TITLE
Design System > Layouts > Responsiveness issues on mobile view on old version

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#650]
## Description

1. While viewing on mobile view card layout is not responsive
2. alignment of cards for mobile devices should be one after the other

## Screenshots

![Image](https://github.com/user-attachments/assets/5df98da2-8dd6-42e8-bca3-6b17f5abddf9)
![Image](https://github.com/user-attachments/assets/405e496d-5c7b-42cf-abfb-d1f296323264)
![Image](https://github.com/user-attachments/assets/afd175fb-90e4-4de1-9d03-3df12a313338)

**Comment by RadhikaB123** [comment]
@Arbaaz-Sayyed  need to implement dynamic mobile screens for mobile sections

**Comment by rameshwarkamandar** [comment]
![Image](https://github.com/user-attachments/assets/406215ed-330d-4ba6-bd45-85981dc8266f)
![Image](https://github.com/user-attachments/assets/b51a96fe-b4c3-4feb-8350-6d3a9fbeb0fc)
![Image](https://github.com/user-attachments/assets/926c6b4f-3857-44be-bfc9-78952a4d29b9)
![Image](https://github.com/user-attachments/assets/29996de0-207a-4291-9859-cc9570845d92)
![Image](https://github.com/user-attachments/assets/f196cf1a-269a-46ff-9dda-5cee3eaab2ac)
![Image](https://github.com/user-attachments/assets/34a85f0a-6ab1-4798-9293-0726f9919745)
![Image](https://github.com/user-attachments/assets/908483b1-926e-4513-a8ba-70c0488e465e)
![Image](https://github.com/user-attachments/assets/3131537a-43db-49a3-87e9-bbf752350c01)
![Image](https://github.com/user-attachments/assets/82f4dcd7-7b37-4ae6-9840-db0f3674c428)
![Image](https://github.com/user-attachments/assets/1bf5d5bf-8d71-424b-9dac-2c7512a675b2)
![Image](https://github.com/user-attachments/assets/f2c87233-20ca-47ea-9e48-1660872ff952)
![Image](https://github.com/user-attachments/assets/fb387e88-6ab0-4d15-9961-807637f936e8)
![Image](https://github.com/user-attachments/assets/f5d6953f-4dd1-45fe-81bb-03c23aef3335)
![Image](https://github.com/user-attachments/assets/f74c2a35-906b-430e-b15d-9be8d268822e)
![Image](https://github.com/user-attachments/assets/5fec95af-38d6-47d2-93eb-07227b61ac57)
