### ISSUE TITLE
Design System > Elements > alert > With icon > Icon stroke field > Icon stroke field is not working

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#651]
**Describe the bug**
Icon stroke field is not working
 
**Steps to reproduce bug**
1.Go to '[[https://stage.raaghu.ai/'](https://stage.raaghu.ai/%27)]'
2. Navigate to Elements > Alert > with icon > icon stroke field
 
**Actual result-**
Icon stroke field is not working
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/be15110f-129a-4f55-837e-5786df1c07bb)

 
**Expected result-**
Icon stroke field should be working

**Comment by suchithravipin1991** [comment]
Duplicate Bug :   Resolved Bug 653 : Design system > Element > alert > With icon/ With close button/With delay Alert > Icon stroke field > Icon stroke button is not working #675
