### ISSUE TITLE
Design system > Element > alert > With icon/ With close button/With delay Alert > Icon stroke field > Icon stroke button is not working

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#653]

**Comment by RadhikaB123** [comment]
**Describe the bug**
Icon stroke button is not working
 
**Steps to reproduce bug**
1.Go to '[[https://stage.raaghu.ai/'](https://stage.raaghu.ai/%27)](https://stage-react.raaghu.ai/?path=/story/elements-alert--with-close-button)'
2. Navigate to 'Element > Alert > With close button > icon stroke'
 
**Actual result-**
Icon stroke button is not working
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/00c0c4c2-d584-429c-a13a-d2f7b7ad116d)

 
**Expected result-**
Icon stroke button should be working

**Comment by rameshwarkamandar** [comment]
Fixed on stage

![image](https://github.com/user-attachments/assets/b37b15e3-4792-44bd-ba43-ff218adb5077)

![image](https://github.com/user-attachments/assets/70cfc075-bc11-4454-8b6e-90b8531a0a56)
