### ISSUE TITLE
Storybook >Components >Claims > Default > Dropdown values are hidden not display proper.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#656]
**Describe the bug**
1. Dropdown values are hidden not display proper.
2. Click on delete icon record is not deleted but action show deleted.

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/?path=/story/components-claims--default'
2. Navigate to 'Storybook >Components >Claims > Default'

**Actual result-**
1. Dropdown values are hidden not display proper.
2. Click on delete icon record is not deleted but action show deleted.

**Screenshots**
![image](https://github.com/user-attachments/assets/9bf29f38-89d5-4968-8133-eaf6d74acb51)

**Expected result-**
1. Dropdown values should be display proper.
2. Click on delete icon record is deleted, and action show deleted.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by dhirajlaha** [comment]
Storybook is for visual testing so deleting a record from a row won't work

**Comment by rameshwarkamandar** [comment]
Completed -

![image](https://github.com/user-attachments/assets/52b83a6c-67b4-4774-9826-26ae9d91acef)
