### ISSUE TITLE
Local environment > Design system > side nav bar > setting icon> misplaced the position of setting icon

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#661]

**Comment by RadhikaB123** [comment]
**Describe the bug**
Misplaced the position of setting icon
 
**Steps to reproduce bug**
1.Go to 'in dev local environment'
2. Navigate to 'side nav bar > setting icon'
 
**Actual result-**
Misplaced the position of setting icon
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/961b838a-3c14-4172-81ab-4d444ee6aa19)

 
**Expected result-**
a setting icon should be besides the pay button

**Comment by RadhikaB123** [comment]
@kaushikgokhale : in dev local environment it is looking like this

**Comment by rameshwarkamandar** [comment]
Fixed on local
![image](https://github.com/user-attachments/assets/8fc1a747-8505-40bf-bd5c-0102cbd3eced)
