### ISSUE TITLE
Design System > Elements > Input > Default > Show icon field > Show icon field is not working

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#663]

**Comment by RadhikaB123** [comment]
**Describe the bug**
Show icon field is not working
 
**Steps to reproduce bug**
1.Go to '[[https://stage.raaghu.ai/'](https://stage.raaghu.ai/%27)](https://stage-react.raaghu.ai/?path=/story/elements-input--default&args=size:small;inputType:email;labelPosition:right;singleDigit:!true)'
2. Navigate to 'Elements > Input > Default'
 
**Actual result-**
Show icon field is not working
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/c4440a8d-ce83-420b-b26a-135a12309ef4)

 
**Expected result-**
Show icon field should be working

**Comment by AkshayPotphode** [comment]
This input field show icon only for input type password. So, this is as per requirement.
