### ISSUE TITLE
Design System > Action Issues

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#678]
Design System > Action Issues
1.I clicked on button for opening off canvas after that label is invisible
2.There is issue in raaghu with action buttons as per designed we cannot add oversize label 
3.Cannot manually enter the value & while binding the value back it is not get assigned.

**Comment by suchithravipin1991** [comment]
Design System > Action Issues
1.I clicked on button for opening off canvas after that label is invisible
2.There is issue in raaghu with action buttons as per designed we cannot add oversize label  
These points are out of scope

**Comment by rameshwarkamandar** [comment]
Fixed on stage

![image](https://github.com/user-attachments/assets/347dab0b-d686-41e8-a146-0f87d9402049)
