### ISSUE TITLE
Design System > Build Verification > [Version 1.1.8.1(s) ] received on 16th Sept 2024

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#686]
Design System > Build Verification > [Version 1.1.8.1(s) ] received on 16th Sept 2024
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Sr.No | To Test   https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8.1(s) | PR ID | Status | Remarks
-- | -- | -- | -- | --
1 | Adding   Action into Development branch by @Shankar1006 in #635 |   |   |  
2 | Resolved   Bug 624 : Issues of Components on Design System by @ashoksinarewai in #626 |   |   |  
3 | Resolved   Bug 591 : Design System > Implement Different Types Rounded Button True   Loading Spinner is not show by @prakashmhaske in #639 |   |   |  
4 | Resolved   Bug 275 : Component > Hide Unused components by @pravinwaghmare23 in #640 |   |   |  
5 | Bug   557 : Resolved Issue Selected Dropdown Value Not Clear After Submitting.   by @ashoksinarewai in #642 |   |   |  
6 | Resolved   Bug 537 & 570 : Hand Cursor is Expected on Mouse Hover & Required   Changes to Rename Permission Tree New Component by @AkshayPotphode in #644 |   |   |  
7 | Bug   567 : Storybook Components Product List Images Alignment Is Not Proper   by @prakashmhaske in #649 |   |   |  
8 | Bug   508 & 539 : Resolved Error Message is Showing Twice in My Settings   Component & Chevron is Not Visible in Select List Element by @AkshayPotphode in #646 |   |   |  
9 | Resolved   Bug 94 : Element > Accordion Default Dropdown Is Expected To Close After   Clicking On It by @prakashmhaske in #645 |   |   |  
10 | Completed   Task : Resolved Compile Error by @Ketan-Khalate in #669 |   |   |  
11 | Completed   Task 610 : Application Shell > Implement Application Shell For Portal To   Storybook In App Shell Section by @prakashmhaske in #641 |   |   |  
12 | Bug   590 : Implement Different Types of Alerts in Storybook Alert Elements   by @AkshayPotphode in #657 |   |   |  
13 | Staging   : Merge Changes from Development to Staging Branch by @Ketan-Khalate in #680 |   |   |  
14 | Resolved   Bug : Run Time Errors by @Ketan-Khalate in #681 |   |   |  
15 | Staging   : Merge Changes from Development to Staging Branch by @Ketan-Khalate in #682 |   |   |  
16 | Completed   Task : Keeping Typescript Version Stable by @Ketan-Khalate in #684 |   |   |  
17 | Staging   : Merge Changes from Development to Staging Branch by @Ketan-Khalate in #685 |   |   |  

</body>

</html>

![Image](https://github.com/user-attachments/assets/7647b39a-0764-4720-b066-364bbf6cbdb0)

**Comment by RadhikaB123** [comment]
![Image](https://github.com/user-attachments/assets/3b9ef6b0-9b08-41ff-81ab-7fec89cf95f9)
