### ISSUE TITLE
Design System > Create design for Layouts

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#696]
Design System > Create design for Layouts

Staging URL for Design System : https://stage-react.raaghu.ai/?path=/story/layouts--sections

**Comment by ShalviPalande1** [comment]
https://www.figma.com/design/RYNs8qwAepJpZ3gduK9imx/Raaghu-Design-System?node-id=2799-7300&t=6GXTp8S2Tnt6EAld-1

RDS/Layouts
