### ISSUE TITLE
Bug : Application Workflows > Component Rendering Issue

### ISSUE THREAD

**Issue by vyankatesh21** [Wai-Technologies/raaghu-react#7]
Go to Storybook - Follow below steps for reproducing the issue

1. Go to Application Workflows
2. Component is not rendering

![Image](https://github.com/Wai-Technologies/raaghu-react/assets/109503161/2c727f96-a6ff-46e5-a06c-e7e6962d7fe5)

**Comment by suraj-khupse** [comment]
Issue Resolved in Current Deployment

**Comment by rameshwarkamandar** [comment]
As this issue already in closed state. closing this now.
