### ISSUE TITLE
Design System > Build Verification > [Version 1.1.8.2(s)] received on 23rd Sept 2024

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#711]
Design System > Build Verification > [Version 1.1.8.2(s)] received on 23rd Sept 2024

[1.1.8.2(s) 🌈](https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8.2(s)) Pre-release

🚀 What's Changed
Bug 671: Storybook > Component > Forms basic > Required message is not display. by @harshitsaini-waiin in https://github.com/Wai-Technologies/raaghu-react/pull/674
Bug 659 : Storybook > Components > Contact Us > Default > Displaying Multiple Error Messages At the One Time by @harshitsaini-waiin in https://github.com/Wai-Technologies/raaghu-react/pull/664
Bug 489: Storybook > Elements >Product Image >Column Layout> Alignment Issue. by @harshitsaini-waiin in https://github.com/Wai-Technologies/raaghu-react/pull/665
Enhancement 529 : Design System > Implement Contributor Component in Storybook by @hemalatagaikwad in https://github.com/Wai-Technologies/raaghu-react/pull/530
Resolved Bug 625 : Design System Issues Of Elements and Charts by @prakashmhaske in https://github.com/Wai-Technologies/raaghu-react/pull/627
Resolved Bug 655 : Billing Address After save clear by @suchithravipin1991 in https://github.com/Wai-Technologies/raaghu-react/pull/672
Resolved Bug 522 : Storybook > Charts > Scatter Chart > Docs > Scatter Chart Icon Does Not Display Proper by @suchithravipin1991 in https://github.com/Wai-Technologies/raaghu-react/pull/677
Added a Contributors File on Root Directory by @BhakareAbhishek in https://github.com/Wai-Technologies/raaghu-react/pull/683
Resolved Bug : Storybook >Components >Claims > Default > Dropdown values are hidden not display proper. by @dhirajlaha in https://github.com/Wai-Technologies/raaghu-react/pull/666
Staging : Merge Changes from Development to Staging Branch by @Ketan-Khalate in https://github.com/Wai-Technologies/raaghu-react/pull/709

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bug /Task ID | Product | Status | Worked on
-- | -- | -- | -- | -- | --
1 | Storybook   > Component > Forms basic > Required message is not display. · Issue   #671 · Wai-Technologies/raaghu-react (github.com) | 671 | Storybook | Reopen | Harshit
2 | Storybook   > Components > Contact Us > Default > Displaying multiple error   messages at the one time. · Issue #659 · Wai-Technologies/raaghu-react   (github.com) | 659 | Storybook | Reopen | Harshit
3 | Storybook   > Elements >Product Image >Column Layout> Alignment Issue. ·   Issue #489 · Wai-Technologies/raaghu-react (github.com) | 489 | Storybook | Closed | Harshit
4 | Storybook   >Component > Billing Address >Default > After submitting field is   not clear. · Issue #655 · Wai-Technologies/raaghu-react (github.com) | 655 | Storybook | Closed | Suchithra
5 | Storybook   >Charts>Scatter Chart>Docs> Scatter Chart icon does not display   proper. · Issue #522 · Wai-Technologies/raaghu-react (github.com) | 522 | Storybook | Reopen | Suchithra
6 | Storybook   >Components >Claims > Default > Dropdown values are hidden not   display proper. · Issue #656 · Wai-Technologies/raaghu-react (github.com) | 656 | Storybook | Closed | Dhiraj
7 | Design   System 7.6.20 > Issues of Elements, chart · Issue #625 ·   Wai-Technologies/raaghu-react (github.com) | 625 | Storybook | Closed | Prakash
8 | Design   System > Implement Contributor Component in Storybook · Issue #529 ·   Wai-Technologies/raaghu-react (github.com) | 529 | Storybook | Closed | Akshay



</body>

</html>
Closed = 5,
Reopen = 3
