### ISSUE TITLE
Storybook > Component > Register Member >Label alignment issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#732]
**Describe the bug**
1. Register Member label alignment issue.
2. Scope Basic Resource label alignment issue.

**Steps to reproduce bug**
1.Go to 'https://stage.raaghu.ai/'
2. Navigate to 'Storybook > Component > Register Member'

**Actual result-**
1. Register Member label alignment issue.
2. Scope Basic Resource label alignment issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/a37e738b-b0c9-4085-9a98-3067f90cc31c)

![image](https://github.com/user-attachments/assets/8410ad68-43f7-47dc-b1fb-c561800c746a)

**Expected result-**
Label should be aligned properly.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by suchithravipin1991** [comment]
This bug is not reproducible in development branch and found in staging only

**Comment by poojagurav21** [comment]
@trivenikulkarni  The bug is not reproducing in development branch. After deployment we need to recheck this bug.

**Comment by trivenikulkarni** [comment]
Verified pass on staging
![image](https://github.com/user-attachments/assets/ea8d66b9-f603-4ba3-b553-57df809ff815)


![image](https://github.com/user-attachments/assets/63e0654e-14e8-41f4-9b8d-08bc95bf8e2a)
