### ISSUE TITLE
Storybook > Charts > Pie Chart > Large mobile view reduces the space.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#736]
**Describe the bug**
Large mobile view reduces the space.

**Steps to reproduce bug**
1.Go to 'https://stage.raaghu.ai/'
2. Navigate to 'Storybook > Charts > Pie Chart'

**Actual result-**
Large mobile view reduces the space.

**Screenshots**
![image](https://github.com/user-attachments/assets/33edbe80-2ff5-4c06-ab8c-2324ab36e09b)

**Expected result-**
Large mobile view reduces the space.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by RadhikaB123** [comment]
Fixed on staging
![Image](https://github.com/user-attachments/assets/167a5d44-63c1-4568-a397-40356697f4d0)
