### ISSUE TITLE
Design System > Version 8.3.3 >Elements> Big Number > Default > Dark theme number is not display proper.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#764]
**Describe the bug**
1.  Big Number > Default > Dark theme number is not displaying proper check all stories.
2. Color Picker > Dark theme border issue.
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/'
3. Navigate to 'Storybook >Elements> Big Number > Default'

**Actual result-**
1. Dark theme number is not displaying proper check all stories.
2. Color Picker > Dark theme border issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/6219787f-8431-4a65-b926-9ad7dd3d4b76)

![image](https://github.com/user-attachments/assets/243cf9a6-e15e-4783-b2e2-6934a645be4e)

**Expected result-**
 Dark theme number should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Verified Pass on Dev
![image](https://github.com/user-attachments/assets/c1477f9d-0873-4971-b078-fab27beb926d)

**Comment by rameshwarkamandar** [comment]
Fixed on stage or dev
![Image](https://github.com/user-attachments/assets/89d09e83-77ae-4693-9b82-ae360fd9deb5)
![Image](https://github.com/user-attachments/assets/78c841d0-ff64-4a9f-8f84-c7f807b9b7c3)

![Image](https://github.com/user-attachments/assets/5b0bcf80-7758-4e59-a687-af4a2f53d35e)
![Image](https://github.com/user-attachments/assets/d1592f5e-276f-4823-9958-d0fd3c4fba4f)
