### ISSUE TITLE
Design System > Create grid which we column resize and show without horizontal scroll

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#765]
Create grid which we column resize and show without horizontal scroll
![Image](https://github.com/user-attachments/assets/b56d6f48-4e56-4e9f-91eb-0a431df264b0)

**Comment by abhijeetjawale1** [comment]
This work item is covered in https://github.com/Wai-Technologies/raaghu-react/issues/1174
