### ISSUE TITLE
Design System > Version 8.3.3 > Component > Account > Default > The data is not appearing in the action tab after clicking on "Save"

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#780]
**Describe the bug**
The data is not appearing in the action tab after clicking on "Save"
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/components-account--default&args=reset:!true'
2. Navigate to 'Component > Account > Default'
3. add data
4. click on save
 
**Actual result-**
The data is not appearing in the action tab after clicking on "Save"
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/26839bce-8f19-4f47-8f7c-147627cd004e)

 
**Expected result-**
The data should appear in the action tab after clicking on "Save"

**Comment by trivenikulkarni** [comment]
![Staging_Accounts](https://github.com/user-attachments/assets/94a6fac6-1db7-4f85-b864-e4a8a8a2ff29)
![Dev_Accounts](https://github.com/user-attachments/assets/223b5442-972a-45c2-b227-5c51f82d524e)

**Comment by poojagurav21** [comment]
@trivenikulkarni  Please Recheck this issue.
 ![Image](https://github.com/user-attachments/assets/65395ff9-f237-4c53-8e79-cae9d3fd3dc2)

**Comment by rameshwarkamandar** [comment]
Fixed on stage/ dev

![Image](https://github.com/user-attachments/assets/e484f1b5-1e69-40d9-9956-a4a81ed43869)

![Image](https://github.com/user-attachments/assets/9e287e9d-cf54-40d2-9098-e54aa9a15a73)
