### ISSUE TITLE
Design System > Elements > Enhancements in Text Editor

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#788]
Design System > Elements > Enhancements in Text Editor
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=382-4674&node-type=canvas&t=ncBHc3XyPjDjE2We-0
Docs	1]  Spinner development different than design
Default	1]  change the sequence of controls 
	2] Background color of controls

**Comment by rameshwarkamandar** [comment]
Implement control remove the stories.

![Image](https://github.com/user-attachments/assets/513983f4-86bf-4e3a-8126-fb7f3ec1ff23)

**Comment by trivenikulkarni** [comment]
Verified on staging that stories are removed and added points in control 
![image](https://github.com/user-attachments/assets/e2bf003d-b428-4f6a-9873-c01ebe7d1ca1)
