### ISSUE TITLE
Design System > Elements > Enhancements in breadcrumb

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#794]
Design System > Elements > Enhancements in breadcrumb
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=1100-15398&node-type=frame&t=84ekWaM7By5ywc4L-0
Docs	1]  Breadcrumbs developement different than design
Default	1] styles are missing Pill Background and square background

![Image](https://github.com/user-attachments/assets/e975a9f5-1b9a-4dd7-9090-45d3c71cd5d6)

**Comment by poojagurav21** [comment]
@hemalatagaikwad  Please consider https://github.com/Wai-Technologies/raaghu-react/pull/872 this pr for the enhancement of breadcrumb , and close https://github.com/Wai-Technologies/raaghu-react/pull/803 this pr as it has some branch issue

**Comment by rameshwarkamandar** [comment]
All Controls are not available as per wireframe.
![Image](https://github.com/user-attachments/assets/64345102-d8ad-46fc-9833-1c2f3a0bf38c)

**Comment by poojagurav21** [comment]
@rameshwarkamandar Layout, State controls are not added as per the discussion with @rahulp34 sir and @trivenikulkarni .

**Comment by rameshwarkamandar** [comment]
Fixed on stage
All controls are working properly.
![Image](https://github.com/user-attachments/assets/9e3013bb-fb68-4b92-918c-4448bdfdf941)
![Image](https://github.com/user-attachments/assets/7bf23e6c-c52a-4b7a-8554-7099dbbf6558)
![Image](https://github.com/user-attachments/assets/da95c742-d52f-48f8-8b7c-286dd54e3ced)
