### ISSUE TITLE
Design System > Elements > Side Navigation > Small and Large mobile view side navigation is not display.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#801]
**Describe the bug**
Small and Large mobile view side navigation is not display.

**Steps to reproduce bug**
1.Go to 'https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Elements > Side Navigation'

**Actual result-**
Small and Large mobile view side navigation is not display.

**Screenshots**
![image](https://github.com/user-attachments/assets/2cb13f1e-06b4-4df9-8319-4d77e0eccdbe)

![image](https://github.com/user-attachments/assets/21270055-27d7-4683-82f7-64636cc3b1bc)

**Expected result-**
Small and Large mobile view side navigation should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by abhijeetjawale1** [comment]
@trivenikulkarni @rameshwarkamandar 
Changing status of this task Todo to resolved because @rahulp34 is already done these changes

**Comment by abhijeetjawale1** [comment]
Attached PR link  -> https://github.com/Wai-Technologies/raaghu-react/pull/961

**Comment by rameshwarkamandar** [comment]
Fixed on stage or dev
![Image](https://github.com/user-attachments/assets/b78dcf6e-c49a-48fe-b1fe-4e106013c737)
![Image](https://github.com/user-attachments/assets/9029d2b9-b63d-4418-bb6e-7775fd848ac4)
![Image](https://github.com/user-attachments/assets/4c206c80-28ca-44bd-bb41-ce8fd7fb7922)
![Image](https://github.com/user-attachments/assets/1a227b0f-1354-4463-bda3-65fcc068b70c)
![Image](https://github.com/user-attachments/assets/853eff4f-f9b6-4548-a7f2-3ca27e8695ef)
![Image](https://github.com/user-attachments/assets/1ec6cc03-ef80-4fb5-8b39-f49a0c42211b)

![Image](https://github.com/user-attachments/assets/fae03dc5-d6c1-4b41-89de-dafbbe76a805)
![Image](https://github.com/user-attachments/assets/380ddc3c-8129-4718-8e09-160e49f02762)
![Image](https://github.com/user-attachments/assets/dc2cd93f-9f5d-4fcb-82e7-e3da8ab3b7ad)
![Image](https://github.com/user-attachments/assets/2c0e30d6-cb10-4485-a10c-39c8350918d2)
![Image](https://github.com/user-attachments/assets/7e6c0144-0c6d-48d2-a385-fb23a88a8125)
