### ISSUE TITLE
Design System > Version 8.3 > Charts > Area Chart > Show error message.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#802]
**Describe the bug**
Show error message.

**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/'
2. Navigate to 'Design System > Version 8.3 > Charts > Area Chart > Controls'

**Actual result-**
Show error message.

**Screenshots**
![image](https://github.com/user-attachments/assets/59e5a182-20b0-4abb-92c6-82e79c005a39)

**Expected result-**
Show gradient proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Verified Pass
![API_Scope_Staging_No_Issue](https://github.com/user-attachments/assets/55564782-6043-4fd0-b29e-efc1cbc123bd)
![API_Scope_Dev](https://github.com/user-attachments/assets/4519017b-f729-4f0e-abe7-a6b33b80d722)
