### ISSUE TITLE
Design System > Version 8.3 >Charts > Stacked Chart > Small and large mobile view chart is not display proper.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#806]
**Describe the bug**
Small and large mobile view stacked chart is not display proper.

**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/'
2. Navigate to 'Components>Premium Support'

**Actual result-**
Small and large mobile view stacked chart is not display proper.

**Screenshots**
![image](https://github.com/user-attachments/assets/229bdeeb-9066-4f1e-b07b-892e2e026e29)

![image](https://github.com/user-attachments/assets/8433cbff-e070-491b-bdce-eafc80f7f87a)

**Expected result-**
Small and large mobile view stacked chart should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by rameshwarkamandar** [comment]
Fixed on stage/ dev
![Image](https://github.com/user-attachments/assets/9801a256-e7b5-4a89-860c-05235fa7a5c8)
![Image](https://github.com/user-attachments/assets/4fa9b162-51e6-4930-a3c3-39da9681e947)

![Image](https://github.com/user-attachments/assets/dde3be34-1985-4830-898c-2b5427d18d4d)
![Image](https://github.com/user-attachments/assets/2928f755-269b-4ea2-945a-c02aec6dbee0)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/7aad2552-c99b-4338-9ec9-0aa8ba19a560)
![image](https://github.com/user-attachments/assets/d27d9a90-206c-4b14-8163-deb24cf6ec58)
