### ISSUE TITLE
Design System > Components > Menus Directories > Default > Small Mobile view > Not able to see action menus

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#811]
**Describe the bug**
These issue both side stage or dev
Not able to see action menus in small mobile view
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/components-menus-directories--default&globals=viewport:mobile2'
2. Navigate to ' Components > Menus Directories > Default > Small Mobile view '
 
**Actual result-**
Not able to see action menus in small mobile view
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/96799d99-2754-4038-a046-bc5c3d77c764)

 
**Expected result-**
action menus should show in small mobile view

**Comment by rameshwarkamandar** [comment]
Verified pass on staging
![Image](https://github.com/user-attachments/assets/6fe2ef0a-bf1f-40c1-83ce-21a19decb93f)

Verified pass on Dev
![Image](https://github.com/user-attachments/assets/2c4c45d5-14d7-4206-a697-dec795151af4)
