### ISSUE TITLE
Design System > Version 8.3 > Component > Product list > Product list with Inline price > small mobile > Not able to see full image

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#814]
**Describe the bug**
Not able to see full image
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/components-product-list--product-list-with-inline-price&globals=viewport:mobile1'
2. Navigate to ' Component > Product list > Product list with Inline price > small mobile '
 
**Actual result-**
Not able to see full image
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/636f165e-db21-4171-9877-b2bd9c4b7b1c)

**Expected result-**
Not able to see full image

**Comment by rameshwarkamandar** [comment]
Issue still exists on stage
![Image](https://github.com/user-attachments/assets/2e81b34a-77b2-430b-8379-eaf31b1d4327)

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![image](https://github.com/user-attachments/assets/16c9a3f6-43e6-4604-8bdf-d256910114f5)

Fixed on dev
![image](https://github.com/user-attachments/assets/25c8e42e-f9ce-4dfc-a3e9-d7f420d5fa86)

**Comment by RadhikaB123** [comment]
Fixed on staging
![image](https://github.com/user-attachments/assets/f2470e95-24f1-473b-9af8-81f112f5a3d8)
