### ISSUE TITLE
Design System > Create common variables for bootstrap utilities

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#822]
Design System > Create common variables for bootstrap utilities 
like headings, border-radius, border, fonts, border-colors which are commonly applicable in all over elements and components

**Comment by rahulp34** [comment]
Created common variables for bootstrap utilities like headings, border-radius, border, fonts, border-colors which are commonly applicable in all over elements and components
https://github.com/Wai-Technologies/raaghu-react/pull/824

**Comment by poojagurav21** [comment]
@trivenikulkarni  @rameshwarkamandar  This bug includes css file changes so can not be tested on dev or stage , so closing this
