### ISSUE TITLE
Design System > Comparison of storybook on Dev 8.3 version along with theme changes and staging storybook version

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#858]
Design System > Comparison of storybook on Dev 8.3 version along with theme changes and staging storybook version

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<style>

</style>
</head>

<div data-id=2580964391 data-pjax="#repo-content-pjax-container"
data-turbo-frame=repo-content-turbo-frame style='box-sizing: border-box;
margin-top:calc(var(--borderWidth-thin)*-1);padding:var(--stack-padding-normal);
border-top:var(--borderWidth-thin) solid var(--borderColor-muted)'>

<div style='box-sizing: border-box;display:flex !important;position:relative'>
<label class="flex-shrink-0 py-2 pl-3  d-none d-md-block" style='box-sizing: border-box;
 font-weight:var(--base-text-weight-semibold, 600);flex-shrink: 0 !important;
 padding-top:var(--base-size-8, 8px) !important;padding-bottom:var(--base-size-8, 8px) !important;
 padding-left:var(--base-size-16, 16px) !important'>
</label>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-left:var(--base-size-16, 16px) !important'></div>

<div style='box-sizing: border-box;flex: 1 1 auto !important;min-width: 0px !important;
important;padding-right:var(--base-size-8, 8px) !important;important;
important'>

<div style='box-sizing: border-box;color:var(--fgColor-muted, var(--color-fg-muted)) !important;
margin-top:var(--base-size-4, 4px) !important;font-size:var(--h6-size, 12px) !important;
display:flex !important'></div>

</div>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-right:var(--base-size-16, 16px) !important;display:flex !important'><span
style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important'>

<div style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important;min-width: 36px'>

<div aria-label="Assigned to rameshwarkamandar and RadhikaB123"
style='box-sizing: border-box;margin-top:var(--base-size-4, 4px) !important;
background-position-x: ;background-position-y: ;background-size: ;background-origin: ;
background-clip: ;border-radius: 100px;display:flex;flex-direction: row-reverse'></div>

</div>

</span></div>

</div>

</div>

<div data-id=2580958721 data-pjax="#repo-content-pjax-container"
data-turbo-frame=repo-content-turbo-frame style='box-sizing: border-box;
margin-top:calc(var(--borderWidth-thin)*-1);padding:var(--stack-padding-normal);
border-top:var(--borderWidth-thin) solid var(--borderColor-muted)'>

<div style='box-sizing: border-box;display:flex !important;position:relative'>
<label class="flex-shrink-0 py-2 pl-3  d-none d-md-block" style='box-sizing: border-box;
 font-weight:var(--base-text-weight-semibold, 600);flex-shrink: 0 !important;
 padding-top:var(--base-size-8, 8px) !important;padding-bottom:var(--base-size-8, 8px) !important;
 padding-left:var(--base-size-16, 16px) !important'>
</label>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-left:var(--base-size-16, 16px) !important'></div>

<div style='box-sizing: border-box;flex: 1 1 auto !important;min-width: 0px !important;
important;padding-right:var(--base-size-8, 8px) !important;important;
important'>

<div style='box-sizing: border-box;color:var(--fgColor-muted, var(--color-fg-muted)) !important;
margin-top:var(--base-size-4, 4px) !important;font-size:var(--h6-size, 12px) !important;
display:flex !important'></div>

</div>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-right:var(--base-size-16, 16px) !important;display:flex !important'><span
style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important'>

<div style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important;min-width: 26px'>

<div aria-label="Assigned to trivenikulkarni" style='box-sizing: border-box;
margin-top:var(--base-size-4, 4px) !important;background-position-x: ;
background-position-y: ;background-size: ;background-origin: ;background-clip: ;
border-radius: 100px;display:flex;flex-direction: row-reverse'></div>

</div>

</span></div>

</div>

</div>

<div data-id=2580670922 data-pjax="#repo-content-pjax-container"
data-turbo-frame=repo-content-turbo-frame style='box-sizing: border-box;
margin-top:calc(var(--borderWidth-thin)*-1);padding:var(--stack-padding-normal);
border-top:var(--borderWidth-thin) solid var(--borderColor-muted)'>

<div style='box-sizing: border-box;display:flex !important;position:relative'>
<label class="flex-shrink-0 py-2 pl-3  d-none d-md-block" style='box-sizing: border-box;
 font-weight:var(--base-text-weight-semibold, 600);flex-shrink: 0 !important;
 padding-top:var(--base-size-8, 8px) !important;padding-bottom:var(--base-size-8, 8px) !important;
 padding-left:var(--base-size-16, 16px) !important'>
</label>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-left:var(--base-size-16, 16px) !important'></div>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-right:var(--base-size-16, 16px) !important;display:flex !important'><span
style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important'>

<div style='box-sizing: border-box;flex-grow: 1 !important;flex-shrink: 0 !important;
flex-basis: 0%;margin-left:var(--base-size-8, 8px) !important;min-width: 26px'>

<div aria-label="Assigned to poojagurav21" style='box-sizing: border-box;
margin-top:var(--base-size-4, 4px) !important;background-position-x: ;
background-position-y: ;background-size: ;background-origin: ;background-clip: ;
border-radius: 100px;display:flex;flex-direction: row-reverse'></div>

</div>

</span></div>

</div>

</div>

<div data-id=2555971672 data-pjax="#repo-content-pjax-container"
data-turbo-frame=repo-content-turbo-frame style='box-sizing: border-box;
margin-top:calc(var(--borderWidth-thin)*-1);padding:var(--stack-padding-normal);
border-top:var(--borderWidth-thin) solid var(--borderColor-muted);border-bottom-left-radius: var(--borderRadius-medium);
border-bottom-right-radius: var(--borderRadius-medium);box-shadow: 2px 0 0 var(--borderColor-accent-emphasis) inset;
background-color:var(--bgColor-muted)'>

<div style='box-sizing: border-box;display:flex !important;position:relative'>
<label class="flex-shrink-0 py-2 pl-3  d-none d-md-block" style='box-sizing: border-box;
 font-weight:var(--base-text-weight-semibold, 600);flex-shrink: 0 !important;
 padding-top:var(--base-size-8, 8px) !important;padding-bottom:var(--base-size-8, 8px) !important;
 padding-left:var(--base-size-16, 16px) !important;font-variant-ligatures: normal;
 font-variant-caps: normal;orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
 text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'>
</label>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-left:var(--base-size-16, 16px) !important;font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;text-align:start;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'></div>

<div style='box-sizing: border-box;flex: 1 1 auto !important;min-width: 0px !important;
important;padding-right:var(--base-size-8, 8px) !important;important;
important;font-variant-ligatures: normal;font-variant-caps: normal;orphans: 2;
text-align:start;widows: 2;-webkit-text-stroke-width: 0px;text-decoration-thickness: initial;
text-decoration-style: initial;text-decoration-color: initial'>

<div style='box-sizing: border-box;color:var(--fgColor-muted, var(--color-fg-muted)) !important;
margin-top:var(--base-size-4, 4px) !important;font-size:var(--h6-size, 12px) !important;
display:flex !important'><span style='box-sizing: border-box'></div>

<div style='box-sizing: border-box;flex-shrink: 0 !important;padding-top:var(--base-size-8, 8px) !important;
padding-right:var(--base-size-16, 16px) !important;white-space-collapse: collapse;
text-wrap: nowrap !important;display:flex !important;font-variant-ligatures: normal;
font-variant-caps: normal;orphans: 2;widows: 2;-webkit-text-stroke-width: 0px;
text-decoration-thickness: initial;text-decoration-style: initial;text-decoration-color: initial'></div>

</div>

</div>

</span></div>

<body link="#467886" vlink="#96607D">


  | Design System > Version 8.3 > Side navigation bar > font   size and font style is not consistent Bug
-- | --
  | #852 opened last   week by RadhikaB123
  |   |   |   |   |   |  
 
  |   |  
 
  | Design System > Version 8.3 > Components > User   delegations/ user permission > Default > Mobile view > Not able to   see text on button Bug
  | #816 opened last   week by RadhikaB123
  |  
  | Design System > Version 8.3 > Components > Top navigation   with search > Default > small/large mobile > Not able to see icons   of top nav bar Bug
  | #815 opened last   week by RadhikaB123
  |  
  | Design System > Version 8.3 > Component > Product list   > Product list with Inline price > small mobile > Not able to see   full image Bug
  | #814 opened last   week by RadhikaB123
  |  
  | Design System > Version 8.3 > Components > Menus   Directories > Default > Small Mobile view > Not able to see action   menus Bug
  | #811 opened last   week by RadhikaB123
  |  
  | Design System > Version 8.3 > Component > Datatable >   Action button on Left side > Not able to see the 'Edit' option after   hovering over the row below in the table Bug
  | #810 opened last   week by RadhikaB123
  |  
  | Design System > Version 8.3 >Charts > Polar Area Chart   > Change theme and size display error massage. Bug
  | #807 opened last   week by rameshwarkamandar
  |  
  | Design System > Version 8.3 >Charts > Stacked Chart >   Small and large mobile view chart is not display proper. Bug
  | #806 opened last   week by rameshwarkamandar
  |  
  | Design System > Version 8.3 > Charts > Boolean Chart >   CenterIcon name is not change. Bug
  | #804 opened last   week by rameshwarkamandar
  |  
  | Design System > Version 8.3 > Charts > Area Chart >   Show error message. Bug
  | #802   by rameshwarkamandar was closed last week
  | 1
  |  
  | Design System > Version 8.3 > Elements > Stat >   Advanced > Small mobile light & dark theme is not display   proper. Bug
  | #792 opened 2 weeks   ago by rameshwarkamandar
  |  
  | Design System > Version 8.3 > Elements > Scrollspy >   Dark theme Go Top button is not visible. Bug
  | #789 opened 2 weeks   ago by rameshwarkamandar
  |  
  | Design System > Version 8.3 > Elements > Label >   Control > All font weight is not working proper. Bug
  | #787 opened 2 weeks   ago by rameshwarkamandar
  |  
  | Design System > Version 8.3 > Scroll bar alignment   issue. Bug
  | #746 opened 3 weeks   ago by rameshwarkamandar
  |  



</body>

</html>
Design System > Version 8.3 > Side navigation bar > font size and font style is not consistent Bug
	[#852 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 > Components > User delegations/ user permission > Default > Mobile view > Not able to see text on button Bug
	[#816 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 > Components > Top navigation with search > Default > small/large mobile > Not able to see icons of top nav bar Bug
	[#815 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 > Component > Product list > Product list with Inline price > small mobile > Not able to see full image Bug
	[#814 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 > Components > Menus Directories > Default > Small Mobile view > Not able to see action menus Bug
	[#811 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 > Component > Datatable > Action button on Left side > Not able to see the 'Edit' option after hovering over the row below in the table Bug
	[#810 opened last week by RadhikaB123](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3ARadhikaB123)
	
	Design System > Version 8.3 >Charts > Polar Area Chart > Change theme and size display error massage. Bug
	[#807 opened last week by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 >Charts > Stacked Chart > Small and large mobile view chart is not display proper. Bug
	[#806 opened last week by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 > Charts > Boolean Chart > CenterIcon name is not change. Bug
	[#804 opened last week by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 > Charts > Area Chart > Show error message. Bug
	[#802 by rameshwarkamandar was closed last week](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+author%3Arameshwarkamandar)
	[ 1](https://github.com/Wai-Technologies/raaghu-react/issues/802)
	
	Design System > Version 8.3 > Elements > Stat > Advanced > Small mobile light & dark theme is not display proper. Bug
	[#792 opened 2 weeks ago by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 > Elements > Scrollspy > Dark theme Go Top button is not visible. Bug
	[#789 opened 2 weeks ago by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 > Elements > Label > Control > All font weight is not working proper. Bug
	[#787 opened 2 weeks ago by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
	
	Design System > Version 8.3 > Scroll bar alignment issue. Bug
	[#746 opened 3 weeks ago by rameshwarkamandar](https://github.com/Wai-Technologies/raaghu-react/issues?q=is%3Aissue+is%3Aopen+author%3Arameshwarkamandar)
