### ISSUE TITLE
Design System > Elements > Benefit > Heading with icon > small mobile > missing space above card

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#860]
**Describe the bug**
missing space above card
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/elements-benefit--heading-with-icon&globals=viewport:mobile1'
2. Go to 'https://stage-react.raaghu.ai/'
3. Navigate to ' Elements > Benefit > Heading with icon > small mobile '
 
**Actual result-**
missing space above card
 
**Screenshots**
Actual result
![Image](https://github.com/user-attachments/assets/77dbbf55-26a4-4e93-9ad1-d69b0c0bfab9)

Expected result
![Image](https://github.com/user-attachments/assets/c7a1e918-b0f0-40fe-ac4a-f55957052822)

**Expected result-**
Space should be same as per staging site

**Comment by VenuKG** [comment]
@trivenikulkarni and @rameshwarkamandar The bug is not reproducing on development and development 8.2 branch

**Comment by VenuKG** [comment]
![image](https://github.com/user-attachments/assets/c67d1555-1324-4361-9a4f-995d1ed9086a)
The bug isn't reproduced on development and development 8.2 branch.

**Comment by trivenikulkarni** [comment]
Verified pass on staging 
![image](https://github.com/user-attachments/assets/9a5deb5c-065f-4f23-96de-e49c3efed1f0)
