### ISSUE TITLE
Design System > Components > Account> Default > Captcha > Required message is not display & Alignment issue validation message Enter valid url.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#861]
**Describe the bug**
1. required message is not display & Alignment issue validation message Enter valid url. 
2 Small large mobile Account Settings General, Account Settings Two Factor, Captcha button does not display proper.

**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Account> Default > Captcha'

**Actual result-**
1. required message is not display & Alignment issue validation message Enter valid url. 
2 Small large mobile Account Settings General, Account Settings Two Factor, Captcha button does not display proper.

**Screenshots**
![image](https://github.com/user-attachments/assets/87332a54-c306-4fce-8868-82b9fde7ec46)

![image](https://github.com/user-attachments/assets/7883ae79-cf62-4d29-b9e8-6cd1b2710768)

![image](https://github.com/user-attachments/assets/60d658e7-afd8-4e7a-964a-ca33ce4d9fc9)

**Expected result-**
1. required message should be display & Alignment issue validation message Enter valid url. 
2 Small large mobile Account Settings General, Account Settings Two Factor, Captcha button should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by poojagurav21** [comment]
@rameshwarkamandar After completing https://github.com/Wai-Technologies/raaghu-react/pull/839 this pull request the issue for alignment of error message will be resolve

**Comment by rameshwarkamandar** [comment]
Closing this bug because of duplicate bug

![Image](https://github.com/user-attachments/assets/a1da0b85-1e8f-473a-81df-02ca6644310c)

![Image](https://github.com/user-attachments/assets/5d65b5e8-6748-4388-b50b-dafa05cd3482)
