### ISSUE TITLE
Design System > Components > Datatable> Action Button on Left Side> Mouse hover edit is hide.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#868]
**Describe the bug**
Check below all component in small & large mouse hover popup is hide.
1. Datatable> Action Button on Left Side / Action Button on Left Side/ List View/ Without Pagination> Mouse hover edit is hide.
2. Pages > Small Mobile view popup is hide.
3. Tenant List > Small Mobile view popup is hide.
4. User Table > Small Mobile view popup is hide.
5. User Permission >Small Mobile view popup is hide.

**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/' & https://dev-react.raaghu.ai/
2. Navigate to 'Design System > Components > Datatable> Action Button on Left Side'

**Actual result-**
Check below all component in small & large mouse hover popup is hide.
1. Datatable> Action Button on Left Side / Action Button on Left Side/ List View/ Without Pagination> Mouse hover edit is hide.
2. Pages > Small Mobile view popup is hide.
3. Tenant List > Small Mobile view popup is hide.
4. User Table > Small Mobile view popup is hide.
5. User Permission >Small Mobile view popup is hide.

**Screenshots**
Stage
![image](https://github.com/user-attachments/assets/b7a52d8c-a519-40ff-a7f8-ff9298d4707d)
![image](https://github.com/user-attachments/assets/133a3837-0770-45d8-838e-da4e13275832)
![image](https://github.com/user-attachments/assets/991a1dcb-6067-4ccf-b89f-2f86e05e2b0c)

dev
![image](https://github.com/user-attachments/assets/637cc5d0-1bd3-48e6-9fcd-4f9aa75fe259)

**Expected result-**
Mouse hover popup should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Assigning to Rahul for CSS changes

**Comment by hemalatagaikwad** [comment]
already resolved
