### ISSUE TITLE
Design System > Charts > Pie chart > Unable to change the size of the pie chart, and for a circle, height and width are not required; only the radius is needed

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#875]
**Describe the bug**
Unable to change the size of the pie chart, and for a circle, height and width are not required; only the radius is needed
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/charts-pie-chart--pie-chart&args=width:300009;height:300000000'
2. Go to 'https://stage-react.raaghu.ai/?path=/story/charts-pie-chart--pie-chart&args=width:30022222222;height:30022222244'
2. Navigate to 'Charts > Pie chart'
3. Enhancement of control to be done as per figma link
 
**Actual result-**
Unable to change the size of the pie chart, and for a circle, height and width are not required; only the radius is needed
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/9ebe9454-2cec-4292-b64a-323fe8cddda8)
![Image](https://github.com/user-attachments/assets/62df5473-4864-4559-91eb-c819cd58bf09)

 
**Expected result-**
Size of pie chart should be changed and radius control should be required
Enhancement of control should be done as per figma link

**Comment by rameshwarkamandar** [comment]
Fixed on stage/ dev

![Image](https://github.com/user-attachments/assets/81a9da7b-fbf1-471d-b7a8-cfcb2cc06da1)
![Image](https://github.com/user-attachments/assets/dffdd089-0c6a-43d4-86f0-f491d4873eb3)
