### ISSUE TITLE
Design System > Charts > Doughnut chart > The title text and subtitle text do not change without refreshing the page

### ISSUE THREAD

**Issue by RadhikaB123** [Wai-Technologies/raaghu-react#878]
**Describe the bug**
The title text and subtitle text do not change without refreshing the page
 
**Steps to reproduce bug**
1.Go to 'https://dev-react.raaghu.ai/?path=/story/charts-pie-chart--pie-chart&args=width:300009;height:300000000'
2. Go to 'https://stage-react.raaghu.ai/?path=/story/charts-pie-chart--pie-chart&args=width:30022222222;height:30022222244'
2. Navigate to 'Charts > Doughnut chart'
3. Enhancement of control to be done as per figma link
 
**Actual result-**
The title text and subtitle text do not change without refreshing the page
 
**Screenshots**
![Image](https://github.com/user-attachments/assets/0595c573-f909-4fae-a77d-3f24376078ad)

![Image](https://github.com/user-attachments/assets/803d89cd-697a-40de-992d-6df5e3757ba6)

 
**Expected result-**
The title text and subtitle text should be change without refreshing the page
Enhancement of control should be done as per figma link

**Comment by abhijeetjawale1** [comment]
@RadhikaB123  @trivenikulkarni 
I have discussion with Shalvi for the figma design she had mentioned -> The design team is in the process of creating charts and maps in figma.

I have made changes for the  -> The title text and subtitle text do not change without refreshing the page. Pending part is enhancement of the chart.

**Comment by rameshwarkamandar** [comment]
Fixed on stage or dev
![Image](https://github.com/user-attachments/assets/de580bdd-aa2a-4a71-aebe-3f29ddcbd35f)

![Image](https://github.com/user-attachments/assets/b9f080fe-2bba-41ad-a41a-59bfcfae8ed5)
