### ISSUE TITLE
Design System > Components > Email > Default > Required msg is not display Validation msg alignment issue. 

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#881]
**Describe the bug**
Required msg is not display Validation msg alignment issue. Tablet view button does not display proper.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Email > Default'

**Actual result-**
Required msg is not display Validation msg alignment issue. Tablet view button does not display proper.

**Screenshots**
stage
![image](https://github.com/user-attachments/assets/fd5f40ea-8227-4704-a8e8-8dfeb3960851)

dev
![image](https://github.com/user-attachments/assets/4135f6a8-d247-42dc-9f47-36d0e758e8b2)

**Expected result-**
Required msg should be display Validation msg alignment issue. Tablet view button should be display proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by poojagurav21** [comment]
@rameshwarkamandar ![Image](https://github.com/user-attachments/assets/ce35d3ae-703c-41d9-86c6-a5b4591cd326)
Fixed this issue in another pr.
Pull request no:- https://github.com/Wai-Technologies/raaghu-react/pull/839/commits

**Comment by rameshwarkamandar** [comment]
Fixed on stage/ dev

![Image](https://github.com/user-attachments/assets/d651a17f-1ea3-4c7b-a9af-0eeb780fe41f)
![Image](https://github.com/user-attachments/assets/0a49871b-8ddd-436e-967c-c519cd82857d)

![Image](https://github.com/user-attachments/assets/45062aad-1c8a-4abf-990d-e50e90ab4e47)
![Image](https://github.com/user-attachments/assets/7c8ee8b0-c0cf-4ca3-bd0e-45de810ad661)
