### ISSUE TITLE
Design System > Components > Shopping Cart > Small large mobile card text & icon is not display proper.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#892]
**Describe the bug**
Below issue staging & dev -
1. Shopping Cart > Small large mobile card text & icon is not display proper.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
62. Navigate to '
Design System > Components > Shopping Cart'

**Actual result-**
1. Shopping Cart > Small large mobile card text & icon is not display proper.

**Screenshots**
stage

![Image](https://github.com/user-attachments/assets/0a4ceaac-f4ea-4235-903d-8e8cabd11563)

**Expected result-**
For Small & large mobile view Card spacing should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by poojagurav21** [comment]
@rameshwarkamandar ![Image](https://github.com/user-attachments/assets/6c136035-0344-414f-ae5a-2a660d2dd404)

**Comment by rameshwarkamandar** [comment]
Fixed on stage/ dev
![Image](https://github.com/user-attachments/assets/53486657-808b-41a2-b9ed-7e47074c9ddd)
![Image](https://github.com/user-attachments/assets/2ea62a45-1037-4036-8101-a0d8ae20876d)
