### ISSUE TITLE
Design System > Components > Claim Type > Default >After submitting field not clear. 

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#898]
**Describe the bug**
 1. Claim Type > Default >After submitting field not clear. 
 2. Language > After submitting field not clear.
 
**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Claim Type > Default> Fill data >Click on save'
3. After Saving highlighted field not clear.

**Actual result-**
 1. Claim Type > Default >After submitting field not clear. 
 2. Language > After submitting field not clear.

**Screenshots**
![image](https://github.com/user-attachments/assets/33784569-85af-40c0-9a89-2814eac3f4c7)
![image](https://github.com/user-attachments/assets/59e6245a-e8d2-48a3-a237-ff0f1d82b980)

**Expected result-**
For Small & large mobile view Card spacing should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Verified pass on Dev
![image](https://github.com/user-attachments/assets/2e6410b7-549d-4c63-9ecf-309aa96cb6c2)

![image](https://github.com/user-attachments/assets/9b17ceb3-9199-4e97-b185-6b45a580b35f)

On staging
![image](https://github.com/user-attachments/assets/6b32bfdd-b8d1-47ab-8e27-872b9e72ef0d)
1. It should be UI instead of Ui
2. Feild alignment is not proper
3. Regex field doesn't have any validation for regular expression

**Comment by DeepashriDatar** [comment]
@trivenikulkarni 
1. It should be UI instead of Ui -Done
2. Feild alignment is not proper -Done
3. Regex field doesn't have any validation for regular expression - the validation will gets added at the time of implementation of this component, as per the new project's requirement

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/1982e2ef-9b40-4d84-b906-ee3197db4b1b)
![Image](https://github.com/user-attachments/assets/3b0c8078-aaa4-4446-aefd-e1ce9e77f220)
Fixed on dev
![Image](https://github.com/user-attachments/assets/e6f4c007-a5a6-4e0a-af55-e568234f7e78)
![Image](https://github.com/user-attachments/assets/df23e5e9-5154-413c-b367-0ab867c56f32)
