### ISSUE TITLE
Design System > Ratings > Enhancements in Ratings.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#905]
Enhancements in Reviews.
https://www.figma.com/design/vziFLZAgMFi8wA5SlikLh5/Raaghu-Design-System?node-id=872-1511&node-type=canvas&t=ZwNLvt8O7PYMZIKM-0

**Comment by abhijeetjawale1** [comment]
@trivenikulkarni  @rameshwarkamandar 
Enhancements have been made to the slider, and new stories have been added for the slider, outline, and filled variations.

Assigning this task to Rahul Patil to make the following changes:

Rating Selection: When selecting a half rating (e.g., 1.5 or 2.5), ensure the half star fills with the appropriate color. Currently, the full star is being filled even when a half rating is selected (e.g., selecting 2.5 fills the 3rd star completely).
Star Outline and Filled Variations: Review and adjust the background colors for the star's outline and filled versions to ensure consistency across different stories.

**Comment by rahulp34** [comment]
@trivenikulkarni  @rameshwarkamandar @abhijeetjawale1 

I have added styling for half filled and also added two new icons in icons.tsx file

https://github.com/user-attachments/assets/a754f227-157e-4b70-b49f-f935a192ca6b

https://github.com/Wai-Technologies/raaghu-react/pull/920

**Comment by rameshwarkamandar** [comment]
Enhancements fixed on stage.
![Image](https://github.com/user-attachments/assets/bb39f3d6-62ac-4834-8c47-eaccf2c680a4)
![Image](https://github.com/user-attachments/assets/7690489f-84a1-44c2-9b5c-30ee472151b1)
![Image](https://github.com/user-attachments/assets/907e25cb-bd56-42c2-876f-c35157ed2cad)
![Image](https://github.com/user-attachments/assets/fde12f0e-8b8a-46dd-bb12-2665aae51f41)
