### ISSUE TITLE
Design System > Introduction > Incorrect text.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#936]
**Describe the bug**
Incorrect text.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Introduction'

**Actual result-**
Incorrect text.

**Screenshots**
![image](https://github.com/user-attachments/assets/0c0517cc-7613-4b23-aa8a-5396a373b124)

**Expected result-**
Text should be correct.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Verified pass on staging
![image](https://github.com/user-attachments/assets/df5ca2de-e698-4b66-bd20-ab14eafb6295)
