### ISSUE TITLE
Design System > Component > Add design for Toolbar

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#959]
Design System > Component > Add design for Toolbar

![Image](https://github.com/user-attachments/assets/637d782e-dcbd-48f9-9020-ed308367ff34)

**Comment by ShalviPalande1** [comment]
Added to Raaghu Design System Figma file under "Details Pane - Toolbar"
![Image](https://github.com/user-attachments/assets/4887568f-cd02-4b4a-9a85-76f0e1efc863)
