### ISSUE TITLE
Design System >Elements > Alert > Default > Incorrect text.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#963]
**Describe the bug**
Incorrect text.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System >Elements > Alert > Default'

**Actual result-**
In correct text.

**Screenshots**
![image](https://github.com/user-attachments/assets/32b0be59-75d2-4c11-aa24-fa7da97ab844)

**Expected result-**
 Text should be correct.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by trivenikulkarni** [comment]
Verified pass on staging 
![image](https://github.com/user-attachments/assets/133d5130-5168-4663-a5cd-4f24c376b47a)
