### ISSUE TITLE
Design System > Components > Admin Dashboard > Button text alignment issue.

### ISSUE THREAD

**Issue by rameshwarkamandar** [Wai-Technologies/raaghu-react#990]
**Describe the bug**
Button text alignment issue.

**Steps to reproduce bug**
1. Go to 'https://dev-react.raaghu.ai/ & https://stage-react.raaghu.ai/'
2. Navigate to 'Design System > Components > Admin Dashboard >Default'

**Actual result-**
Button text alignment issue.

**Screenshots**
![image](https://github.com/user-attachments/assets/5063e9c5-5317-4c35-b063-2c47c20c8def)

**Expected result-**
Button text alignment should be proper.

**Desktop (please complete the following information):**
-OS: [Windows 10 Enterprise]
-Browser [ edge]
-Version [ 125.0.2535.92]

**Comment by hemalatagaikwad** [comment]
Resolved issue on PR https://github.com/Wai-Technologies/raaghu-react/pull/1031
