### ISSUE TITLE
Design System > Build Verification 1.1.8.5

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#992]
Design System > Build Verification 1.1.8.5
https://github.com/Wai-Technologies/raaghu-react/releases/tag/1.1.8.5(s)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">

Sr.No | Github |   | Status | Remark | Dev | QA
-- | -- | -- | -- | -- | -- | --
1 | Resolved   Bug 870 : Design System > Components > Dynamic Entity Properties>   Default> Small, Large mobile overlap Parameter. by @poojagurav21 in #910 |   |   |   |   | Rameshwar
2 | Resolved   Bug 898 : Design System > Components > Claim Type & Language >   Default > After submission dropdown field does not clear by @DeepashriDatar in #904 |   |   |   |   | Rameshwar
3 | Resolved   Bug 894 : Component > Visual Setting > default > mobile view (small   & large) footer overlapping issue by @DeepashriDatar in #899 |   |   |   |   | Rameshwar
4 | Completed   Task 592 : Design System > Implement different types of Avtars by @abhijeetjawale1 in #912 |   |   |   |   | Rameshwar
5 | Build   Issues : Resolved Errors on Development Branch by @abhijeetjawale1 in #924 |   |   |   |   | Rameshwar
6 | Completed   Task 905 : Design System > Ratings > Enhancements in Ratings by @abhijeetjawale1 in #915 |   |   |   |   | Rameshwar
7 | Resolved   Bug 889 : Design System > Components > Secrets > Default > Save   cancel button alignment issue. by @poojagurav21 in #923 |   |   |   |   | Rameshwar
8 | Completed   Task 590 : Design System > Enhancement > Implement different types of   Alerts (For small & large mobile views) by @DeepashriDatar in #930 |   |   |   |   | Rameshwar
9 | Resolved   Bug 884 : Design System > Components > Premium Support> Default >   Large mobile view card alignment is not display proper by @DeepashriDatar in #928 |   |   |   |   | Rameshwar
10 | Resolved   Bug 926 : Storybook > Components > Summary Details > Default >   Incorrect Text. by @abhijeetjawale1 in #927 |   |   |   |   | Rameshwar
11 | Resolved   Bug 660 & 844 : Storybook > Components > Change Password >   Default > Error message alignment issue & Design System >   Components > Register Member > Default > Display twice error message   by @poojagurav21 in #922 |   |   |   |   | Rameshwar
12 | Resolved   Bug 807: Design System > Charts > Polar Area Chart > Change theme   and size display error massage. by @abhijeetjawale1 in #946 |   |   |   |   | Rameshwar
13 | Resolved   Bug 172 : Storybook > Component > Account > Default > Captcha   > Issues on Account component Small, Large mobile view captcha not   visible. by @poojagurav21 in #932 |   |   |   |   | Rameshwar
14 | Resolved   Bug 746 : Design System > Version 8.3 > Scroll bar alignment issue.   by @poojagurav21 in #951 |   |   |   |   | Rameshwar
15 | Resolved   Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top   button is not visible by @abhijeetjawale1 in #943 |   |   |   |   | Rameshwar
16 | Completed   Task 690 : Design System > Components > Data Table > Add new   component for Action by @abhijeetjawale1 in #940 |   |   |   |   | Rameshwar
17 | Resolved   Bug 792 : Design System > Elements > Stat > Advanced > Small   mobile light & dark theme is not display proper by @abhijeetjawale1 in #950 |   |   |   |   | Rameshwar
18 | Resolved   Bug 811 : Design System > Components > Menus Directories > Default   > Small Mobile view > Not able to see action menus by @abhijeetjawale1 in #948 |   |   |   |   | Rameshwar
19 | Resolved   Bug 935 : Design System > Components > Add Member > Button alignment   issue by @abhijeetjawale1 in #941 |   |   |   |   | Rameshwar
20 | Completed   Task 776 : Design System > Elements > Enhancements in Toast by @DeepashriDatar in #819 |   |   |   |   | Rameshwar
21 | Completed   Bug 867 : Design System > Components > Collapsible Container >   Default> UI issue and subscribe to icon color is light. by @rahulp34 in #913 |   |   |   |   | Triveni
22 | Resolved   Bug 94 : Element > Accordion > Default > Dropdown is expected to   close after clicking on it by @rahulp34 in #917 |   |   |   |   | Triveni
23 | Completed   Task 778 : Design System > Elements > Enhancements in Spinner by @prakashmhaske in #838 |   |   |   |   | Triveni
24 | Resolved   Bug 893 : Design System > Components > Tenant Dashboard > Default   > Small mobile view Todo list issue by @prakashmhaske in #916 |   |   |   |   | Triveni
25 | Resolved   Bug 820 : Design System > Elements > Side navigation enhancements   by @rahulp34 in #961 |   |   |   |   | Triveni
26 | Resolved   Bug 882 : Design System > Components > File Management Tree >   Default > Small large view does not display proper. by @poojagurav21 in #921 |   |   |   |   | Triveni
27 | Resolved   Bug 936 : Design System > Introduction > Incorrect text by @nitinsonawane123 in #970 |   |   |   |   | Triveni
28 | Resolved   Bug 963 : Design System >Elements > Alert > Default > Incorrect   text by @nitinsonawane123 in #966 |   |   |   |   | Triveni
29 | Resolved   Bug 804 : Design System > Version 8.3 > Charts > Boolean Chart >   CenterIcon Icon is not change. #804 by @nitinsonawane123 in #953 |   |   |   |   | Triveni
30 | Resolved   Bug 747 : Design System > Elements > Accordion > Border is not   visible proper. by @abhijeetjawale1 in #974 |   |   |   |   | Triveni
31 | Resolved   Bug 787 : Design System > Version 8.3 > Elements > Feed > For   Small & large mobile view text alignment is not proper and duplicate text   is displayed by @poojagurav21 in #947 |   |   |   |   | Triveni
32 | Resolved   Bug 732 : Storybook > Component > Register Member >Label alignment   issue. by @poojagurav21 in #944 |   |   |   |   | Triveni
33 | Resolved   Bug 764 : Design System > Version 8.3.3 >Elements> Big Number >   Default > Dark theme number is not display proper by @poojagurav21 in #945 |   |   |   |   | Triveni
34 | Completed   Task 900 : Design System > Element > Create new element Time Picker   by @abhijeetjawale1 in #934 |   |   |   |   | Triveni
35 | Completed   Task 788 : Design System > Elements > Enhancements in Text Editor   by @poojagurav21 in #933 |   |   |   |   | Triveni
36 | Resolved   Bug 871 : Design System > Components > Required message is not   displaying, & validation message alignment issue by @poojagurav21 in #929 |   |   |   |   | Triveni
37 | Resolved   Bug 883 : Design System > Components > Invoice Detail Receipt>   Default >Dark theme text is not display proper by @poojagurav21 in #909 |   |   |   |   | Triveni
38 | Resolved   Bug 958 : Design System > Database Connection > Default > Connection   Strings spacing issue by @VenuKG in #967 |   |   |   |   | Triveni
39 | Resolved   Bug 866 : Design System > Components > Background Image > Default   >Light theme selected text is not display Proper by @rahulp34 in #914 |   |   |   |   | Triveni
40 | Merge   Development : Moving Changes from Development to Staging Branch by @hemalatagaikwad in #982 |   |   |   |   | Triveni

</body>

</html>

**Comment by trivenikulkarni** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


1 | Design   System > Components > Claim Type > Default >After submitting   field not clear. · Issue #898 · Wai-Technologies/raaghu-react | Reopen
-- | -- | --
2 | Design   System > Components > Background Image > Default >Light theme   selected text is not display Proper. · Issue #866 ·   Wai-Technologies/raaghu-react | Reopen
3 | Design   System > Elements > Benefit > Heading with icon > small mobile   > missing space above card · Issue #860 · Wai-Technologies/raaghu-react | Ready for Prod



</body>

</html>
1	[Design System > Components > Claim Type > Default >After submitting field not clear. · Issue #898 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/898)	Reopen
2	[Design System > Components > Background Image > Default >Light theme selected text is not display Proper. · Issue #866 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/866)	Reopen
3	[Design System > Elements > Benefit > Heading with icon > small mobile > missing space above card · Issue #860 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/860)	Ready for Prod

**Comment by trivenikulkarni** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/TRIVEN~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


4 | (1) Design   System > Components > Visual Setting> Default > Small large   mobile Subheader Footer overlap. · Issue #894 · Wai-Technologies/raaghu-react | Reopen
-- | -- | --
5 | Design   System > Add new component (Grid) · Issue #483 ·   Wai-Technologies/raaghu-react | Reopen



</body>

</html>
4	[(1) Design System > Components > Visual Setting> Default > Small large mobile Subheader Footer overlap. · Issue #894 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/894)	Reopen
5	[Design System > Add new component (Grid) · Issue #483 · Wai-Technologies/raaghu-react](https://github.com/Wai-Technologies/raaghu-react/issues/483)	Reopen

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bug /Task ID | State | Product | Worked on
-- | -- | -- | -- | -- | --
1 | Resolved   Bug 870 : Design System > Components > Dynamic Entity Properties>   Default> Small, Large mobile overlap Parameter. by @poojagurav21 in #910 | 870 | Closed | Storybook | Pooja
2 | Resolved   Bug 889 : Design System > Components > Secrets > Default > Save   cancel button alignment issue. by @poojagurav21 in #923 | 889 | Closed | Storybook | Pooja
3 | Resolved   Bug 926 : Storybook > Components > Summary Details > Default >   Incorrect Text. by @abhijeetjawale1 in #927 | 926 | Closed | Storybook | Abhijeet
4 | Resolved   Bug 660 & 844 : Storybook > Components > Change Password >   Default > Error message alignment issue & Design System >   Components > Register Member > Default > Display twice error message   by @poojagurav21 in #922 | 660 | Closed | Storybook | Pooja
5 | Resolved   Bug 172 : Storybook > Component > Account > Default > Captcha   > Issues on Account component Small, Large mobile view captcha not   visible. by @poojagurav21 in #932 | 172 | Closed | Storybook | Pooja
6 | Resolved   Bug 792 : Design System > Elements > Stat > Advanced > Small   mobile light & dark theme is not display proper by @abhijeetjawale1 in #950 | 792 | Closed | Storybook | Abhijeet
7 | Resolved   Bug 811 : Design System > Components > Menus Directories > Default   > Small Mobile view > Not able to see action menus by @abhijeetjawale1 in #948 | 811 | Closed | Storybook | Abhijeet
8 | Resolved   Bug 935 : Design System > Components > Add Member > Button alignment   issue by @abhijeetjawale1 in #941 | 935 | Closed | Storybook | Abhijeet
9 | Design System > Elements   > Side Navigation > Small and Large mobile view side navigation is not   display. · Issue #801 · Wai-Technologies/raaghu-react | 801 | Closed | Storybook | Abhijeet
10 | Resolved Bug   787 : Design System > Version 8.3 > Elements > Feed > For Small   & large mobile view text alignment is not proper and duplicate text is   displayed by @poojagurav21 in #947 | 787 | Closed | Storybook | Pooja
11 | Resolved   Bug 764 : Design System > Version 8.3.3 >Elements> Big Number >   Default > Dark theme number is not display proper by @poojagurav21 in #945 | 764 | Closed | Storybook | Pooja
12 | Resolved   Bug 883 : Design System > Components > Invoice Detail Receipt>   Default >Dark theme text is not display proper by @poojagurav21 in #909 | 833 | Closed | Storybook | Pooja
13 | Resolved   Bug 660 & 844 : Storybook > Components > Change Password >   Default > Error message alignment issue & Design System >   Components > Register Member > Default > Display twice error message   by @poojagurav21 in #922 | 844 | Closed | Storybook | Pooja
14 | Resolved   Bug 804 : Design System > Version 8.3 > Charts > Boolean Chart >   CenterIcon Icon is not change. #804 by @nitinsonawane123 in #953 | 804 | Closed | Storybook | Nitin
15 | Design System > Version   8.3.3 > Elements > Button Group > Checkbox Button Group > Dark   theme border alignment issue. · Issue #750 · Wai-Technologies/raaghu-react   (github.com) | 750 | Closed | Storybook | Abhijeet
16 | Design System > Charts >   Doughnut chart > The title text and subtitle text do not change without   refreshing the page · Raaghu Design System (github.com) | 878 | Closed | Storybook | Abhijeet
17 | Design System > Layouts >   Responsiveness issues on mobile view on old version · Raaghu Design System   (github.com) | 650 | Closed | Storybook | Rohit
  |   |   |   |   |  
  |   |   |   |   |  
  |   |   |   |   |  
Sr.No | Bug Title | Bug /Task ID | State | Product | Worked on
1 | Resolved   Bug 746 : Design System > Version 8.3 > Scroll bar alignment issue.   by @poojagurav21 in #951 | 746 | Reopen | Storybook | Pooja
2 | Resolved   Bug 789 : Design System > Elements > Scrollspy > Dark theme Go Top   button is not visible by @abhijeetjawale1 in #943 | 789 | Reopen | Storybook | Abhijeet
3 | Completed   Task 690 : Design System > Components > Data Table > Add new   component for Action by @abhijeetjawale1 in #940 | 690 | Reopen | Storybook | Abhijeet
4 | Design System > Elements   > Enhancements in Text Editor · Raaghu Design System (github.com) | 788 | Reopen | Storybook | Pooja
5 | Design System > Elements   > Enhancements in breadcrumb · Raaghu Design System (github.com) | 794 | Reopen | Storybook | Pooja
6 | Resolved   Bug 807: Design System > Charts > Polar Area Chart > Change theme   and size display error massage. by @abhijeetjawale1 in #946 | 807 | Reopen | Storybook | Abhijeet



</body>

</html>

**Comment by rameshwarkamandar** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/RAMESH~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Sr.No | Bug Title | Bug /Task ID | State | Product | Assigned to
-- | -- | -- | -- | -- | --
1 | Design   System > Components > Required message is not displaying, &   validation message alignment issue, · Raaghu Design System | 871 | Closed | Storybook | Pooja
2 | Design   System > Implement different types of Avtaars · Raaghu Design System | 592 | Reopen | Storybook | Abhijeet
3 | Design   System > Element > Create new element Time Picker. · Raaghu Design   System | 900 | Reopen | Storybook | Abhijeet
4 | Design   System > Ratings > Enhancements in Ratings. · Raaghu Design System | 905 | Closed | Storybook | Abhijeet
5 | Design   System > Elements > Enhancements in Toast · Raaghu Design System | 776 | Closed | Storybook | Rahul
6 | Design   System > Components > File Management Tree > Default > Small   large view does not display proper. · Issue #882 ·   Wai-Technologies/raaghu-react | 882 | Closed | Storybook | Pooja
7 | Design   System > Components > Premium Support> Default > Large mobile   view card alignment is not display proper. · Raaghu Design System | 884 | Closed | Storybook | Deepashri
8 | Design   System > Version 8.3 > Component > Product list > Product list   with Inline price > small mobile > Not able to see full image · Raaghu   Design System | 814 | Reopen | Storybook | Nitin
9 | Design   System > Components > Visual Setting> Default > Small large   mobile Subheader Footer overlap. · Raaghu Design System | 894 | Reopen | Storybook | Deepashri
10 | Design   System > Implement different types of Alerts · Raaghu Design System | 590 | Reopen | Storybook | Deepashri



</body>

</html>
