### ISSUE TITLE
Design System > Element > Add new element for header

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#995]
Design System > Element > Add new element for header
1. Only header
2. Header with icon
3. Controls to be added
H1 to H6
Icon : Yes No
icon Position  : left , Right, top, bottom

**Comment by rameshwarkamandar** [comment]
Fixed on stage
All controls working properly. 
![Image](https://github.com/user-attachments/assets/49b9067a-d787-4b9b-99b4-5fa8c57a85d2)
![Image](https://github.com/user-attachments/assets/6e3145ac-fb45-43f4-89b9-13a813687c3d)
