### ISSUE TITLE
Design System > Element > Enhancement in Divider

### ISSUE THREAD

**Issue by trivenikulkarni** [Wai-Technologies/raaghu-react#996]
Design System > Element > Enhancement in Divider 

![Image](https://github.com/user-attachments/assets/e89778b6-e35e-474a-8a3d-1d44f377fe41)

Control to be added 
1. Icon : True , False

**Comment by rameshwarkamandar** [comment]
Fixed on stage
![Image](https://github.com/user-attachments/assets/e2f02bf6-ff9b-4976-8308-66b2efa4ab25)
![Image](https://github.com/user-attachments/assets/e8f37018-abfb-440e-a233-7e1234822874)
